package com.el.cfg.mapper;

import com.el.cfg.domain.TAddressBook;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TAddressBookMapper {
    @Delete({
        "delete from T_ADDRESS_BOOK",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into T_ADDRESS_BOOK (ID, OU_ID, ",
        "MCU_ID, ADDR_NO, LADDR_NO, ",
        "ADDR_NAME, ADDR_ABBR, ",
        "ADDR_CLASS, REL_ADDR_NO1, ",
        "REL_ADDR_NO2, REL_ADDR_NO3, ",
        "REL_ADDR_NO4, REL_ADDR_NO5, ",
        "REL_ADDR_NO6, CAT1, ",
        "CAT2, CAT3, CAT4, ",
        "CAT5, CAT6, CAT7, ",
        "CAT8, CAT9, CAT10, ",
        "CAT11, CAT12, CAT13, ",
        "CAT14, CAT15, CAT16, ",
        "CAT17, CAT18, CAT19, ",
        "CAT20, CAT21, CAT22, ",
        "CAT23, CAT24, CAT25, ",
        "CAT26, CAT27, CAT28, ",
        "CAT29, CAT30, LOCKER_ID, ",
        "LOCK_TS, MODIFYER_ID, ",
        "MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION)",
        "values (#{id,jdbcType=DECIMAL}, #{ouId,jdbcType=DECIMAL}, ",
        "#{mcuId,jdbcType=DECIMAL}, #{addrNo,jdbcType=DECIMAL}, #{laddrNo,jdbcType=NCHAR}, ",
        "#{addrName,jdbcType=NCHAR}, #{addrAbbr,jdbcType=NCHAR}, ",
        "#{addrClass,jdbcType=NCHAR}, #{relAddrNo1,jdbcType=DECIMAL}, ",
        "#{relAddrNo2,jdbcType=DECIMAL}, #{relAddrNo3,jdbcType=DECIMAL}, ",
        "#{relAddrNo4,jdbcType=DECIMAL}, #{relAddrNo5,jdbcType=DECIMAL}, ",
        "#{relAddrNo6,jdbcType=DECIMAL}, #{cat1,jdbcType=NCHAR}, ",
        "#{cat2,jdbcType=NCHAR}, #{cat3,jdbcType=NCHAR}, #{cat4,jdbcType=NCHAR}, ",
        "#{cat5,jdbcType=NCHAR}, #{cat6,jdbcType=NCHAR}, #{cat7,jdbcType=NCHAR}, ",
        "#{cat8,jdbcType=NCHAR}, #{cat9,jdbcType=NCHAR}, #{cat10,jdbcType=NCHAR}, ",
        "#{cat11,jdbcType=NCHAR}, #{cat12,jdbcType=NCHAR}, #{cat13,jdbcType=NCHAR}, ",
        "#{cat14,jdbcType=NCHAR}, #{cat15,jdbcType=NCHAR}, #{cat16,jdbcType=NCHAR}, ",
        "#{cat17,jdbcType=NCHAR}, #{cat18,jdbcType=NCHAR}, #{cat19,jdbcType=NCHAR}, ",
        "#{cat20,jdbcType=NCHAR}, #{cat21,jdbcType=NCHAR}, #{cat22,jdbcType=NCHAR}, ",
        "#{cat23,jdbcType=NCHAR}, #{cat24,jdbcType=NCHAR}, #{cat25,jdbcType=NCHAR}, ",
        "#{cat26,jdbcType=NCHAR}, #{cat27,jdbcType=NCHAR}, #{cat28,jdbcType=NCHAR}, ",
        "#{cat29,jdbcType=NCHAR}, #{cat30,jdbcType=NCHAR}, #{lockerId,jdbcType=DECIMAL}, ",
        "#{lockTs,jdbcType=TIMESTAMP}, #{modifyerId,jdbcType=DECIMAL}, ",
        "#{modifyTs,jdbcType=TIMESTAMP}, #{modifyAppsvr,jdbcType=NCHAR}, ",
        "#{modifyModule,jdbcType=NCHAR}, #{dataVersion,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT SEQ_T_ADDRESS_BOOK.NEXTVAL FROM DUAL", keyProperty="id", before=true, resultType=Long.class)
    int insert(TAddressBook record);

    @Select({
        "select",
        "ID, OU_ID, MCU_ID, ADDR_NO, LADDR_NO, ADDR_NAME, ADDR_ABBR, ADDR_CLASS, REL_ADDR_NO1, ",
        "REL_ADDR_NO2, REL_ADDR_NO3, REL_ADDR_NO4, REL_ADDR_NO5, REL_ADDR_NO6, CAT1, ",
        "CAT2, CAT3, CAT4, CAT5, CAT6, CAT7, CAT8, CAT9, CAT10, CAT11, CAT12, CAT13, ",
        "CAT14, CAT15, CAT16, CAT17, CAT18, CAT19, CAT20, CAT21, CAT22, CAT23, CAT24, ",
        "CAT25, CAT26, CAT27, CAT28, CAT29, CAT30, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, ",
        "MODIFY_APPSVR, MODIFY_MODULE, DATA_VERSION",
        "from T_ADDRESS_BOOK",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCU_ID", property="mcuId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ADDR_NO", property="addrNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="LADDR_NO", property="laddrNo", jdbcType=JdbcType.NCHAR),
        @Result(column="ADDR_NAME", property="addrName", jdbcType=JdbcType.NCHAR),
        @Result(column="ADDR_ABBR", property="addrAbbr", jdbcType=JdbcType.NCHAR),
        @Result(column="ADDR_CLASS", property="addrClass", jdbcType=JdbcType.NCHAR),
        @Result(column="REL_ADDR_NO1", property="relAddrNo1", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO2", property="relAddrNo2", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO3", property="relAddrNo3", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO4", property="relAddrNo4", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO5", property="relAddrNo5", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO6", property="relAddrNo6", jdbcType=JdbcType.DECIMAL),
        @Result(column="CAT1", property="cat1", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT2", property="cat2", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT3", property="cat3", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT4", property="cat4", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT5", property="cat5", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT6", property="cat6", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT7", property="cat7", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT8", property="cat8", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT9", property="cat9", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT10", property="cat10", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT11", property="cat11", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT12", property="cat12", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT13", property="cat13", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT14", property="cat14", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT15", property="cat15", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT16", property="cat16", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT17", property="cat17", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT18", property="cat18", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT19", property="cat19", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT20", property="cat20", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT21", property="cat21", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT22", property="cat22", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT23", property="cat23", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT24", property="cat24", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT25", property="cat25", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT26", property="cat26", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT27", property="cat27", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT28", property="cat28", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT29", property="cat29", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT30", property="cat30", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    TAddressBook selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, OU_ID, MCU_ID, ADDR_NO, LADDR_NO, ADDR_NAME, ADDR_ABBR, ADDR_CLASS, REL_ADDR_NO1, ",
        "REL_ADDR_NO2, REL_ADDR_NO3, REL_ADDR_NO4, REL_ADDR_NO5, REL_ADDR_NO6, CAT1, ",
        "CAT2, CAT3, CAT4, CAT5, CAT6, CAT7, CAT8, CAT9, CAT10, CAT11, CAT12, CAT13, ",
        "CAT14, CAT15, CAT16, CAT17, CAT18, CAT19, CAT20, CAT21, CAT22, CAT23, CAT24, ",
        "CAT25, CAT26, CAT27, CAT28, CAT29, CAT30, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, ",
        "MODIFY_APPSVR, MODIFY_MODULE, DATA_VERSION",
        "from T_ADDRESS_BOOK"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCU_ID", property="mcuId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ADDR_NO", property="addrNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="LADDR_NO", property="laddrNo", jdbcType=JdbcType.NCHAR),
        @Result(column="ADDR_NAME", property="addrName", jdbcType=JdbcType.NCHAR),
        @Result(column="ADDR_ABBR", property="addrAbbr", jdbcType=JdbcType.NCHAR),
        @Result(column="ADDR_CLASS", property="addrClass", jdbcType=JdbcType.NCHAR),
        @Result(column="REL_ADDR_NO1", property="relAddrNo1", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO2", property="relAddrNo2", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO3", property="relAddrNo3", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO4", property="relAddrNo4", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO5", property="relAddrNo5", jdbcType=JdbcType.DECIMAL),
        @Result(column="REL_ADDR_NO6", property="relAddrNo6", jdbcType=JdbcType.DECIMAL),
        @Result(column="CAT1", property="cat1", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT2", property="cat2", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT3", property="cat3", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT4", property="cat4", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT5", property="cat5", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT6", property="cat6", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT7", property="cat7", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT8", property="cat8", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT9", property="cat9", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT10", property="cat10", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT11", property="cat11", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT12", property="cat12", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT13", property="cat13", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT14", property="cat14", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT15", property="cat15", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT16", property="cat16", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT17", property="cat17", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT18", property="cat18", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT19", property="cat19", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT20", property="cat20", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT21", property="cat21", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT22", property="cat22", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT23", property="cat23", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT24", property="cat24", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT25", property="cat25", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT26", property="cat26", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT27", property="cat27", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT28", property="cat28", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT29", property="cat29", jdbcType=JdbcType.NCHAR),
        @Result(column="CAT30", property="cat30", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    List<TAddressBook> selectAll();

    @Update({
        "update T_ADDRESS_BOOK",
        "set OU_ID = #{ouId,jdbcType=DECIMAL},",
          "MCU_ID = #{mcuId,jdbcType=DECIMAL},",
          "ADDR_NO = #{addrNo,jdbcType=DECIMAL},",
          "LADDR_NO = #{laddrNo,jdbcType=NCHAR},",
          "ADDR_NAME = #{addrName,jdbcType=NCHAR},",
          "ADDR_ABBR = #{addrAbbr,jdbcType=NCHAR},",
          "ADDR_CLASS = #{addrClass,jdbcType=NCHAR},",
          "REL_ADDR_NO1 = #{relAddrNo1,jdbcType=DECIMAL},",
          "REL_ADDR_NO2 = #{relAddrNo2,jdbcType=DECIMAL},",
          "REL_ADDR_NO3 = #{relAddrNo3,jdbcType=DECIMAL},",
          "REL_ADDR_NO4 = #{relAddrNo4,jdbcType=DECIMAL},",
          "REL_ADDR_NO5 = #{relAddrNo5,jdbcType=DECIMAL},",
          "REL_ADDR_NO6 = #{relAddrNo6,jdbcType=DECIMAL},",
          "CAT1 = #{cat1,jdbcType=NCHAR},",
          "CAT2 = #{cat2,jdbcType=NCHAR},",
          "CAT3 = #{cat3,jdbcType=NCHAR},",
          "CAT4 = #{cat4,jdbcType=NCHAR},",
          "CAT5 = #{cat5,jdbcType=NCHAR},",
          "CAT6 = #{cat6,jdbcType=NCHAR},",
          "CAT7 = #{cat7,jdbcType=NCHAR},",
          "CAT8 = #{cat8,jdbcType=NCHAR},",
          "CAT9 = #{cat9,jdbcType=NCHAR},",
          "CAT10 = #{cat10,jdbcType=NCHAR},",
          "CAT11 = #{cat11,jdbcType=NCHAR},",
          "CAT12 = #{cat12,jdbcType=NCHAR},",
          "CAT13 = #{cat13,jdbcType=NCHAR},",
          "CAT14 = #{cat14,jdbcType=NCHAR},",
          "CAT15 = #{cat15,jdbcType=NCHAR},",
          "CAT16 = #{cat16,jdbcType=NCHAR},",
          "CAT17 = #{cat17,jdbcType=NCHAR},",
          "CAT18 = #{cat18,jdbcType=NCHAR},",
          "CAT19 = #{cat19,jdbcType=NCHAR},",
          "CAT20 = #{cat20,jdbcType=NCHAR},",
          "CAT21 = #{cat21,jdbcType=NCHAR},",
          "CAT22 = #{cat22,jdbcType=NCHAR},",
          "CAT23 = #{cat23,jdbcType=NCHAR},",
          "CAT24 = #{cat24,jdbcType=NCHAR},",
          "CAT25 = #{cat25,jdbcType=NCHAR},",
          "CAT26 = #{cat26,jdbcType=NCHAR},",
          "CAT27 = #{cat27,jdbcType=NCHAR},",
          "CAT28 = #{cat28,jdbcType=NCHAR},",
          "CAT29 = #{cat29,jdbcType=NCHAR},",
          "CAT30 = #{cat30,jdbcType=NCHAR},",
          "LOCKER_ID = #{lockerId,jdbcType=DECIMAL},",
          "LOCK_TS = #{lockTs,jdbcType=TIMESTAMP},",
          "MODIFYER_ID = #{modifyerId,jdbcType=DECIMAL},",
          "MODIFY_TS = #{modifyTs,jdbcType=TIMESTAMP},",
          "MODIFY_APPSVR = #{modifyAppsvr,jdbcType=NCHAR},",
          "MODIFY_MODULE = #{modifyModule,jdbcType=NCHAR},",
          "DATA_VERSION = #{dataVersion,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TAddressBook record);
}