package com.el.cfg.mapper;

import com.el.cfg.domain.TOrgPart;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TOrgPartMapper {
    @Delete({
        "delete from T_ORG_PART",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into T_ORG_PART (ID, PROD_ID, ",
        "LINE_NO, PART_TYPE, ",
        "PART_CODE, PART_NAME, ",
        "PAGE_CNT, COLORCNT_FRONT, ",
        "COLORCNT_BACK, SCOLORCNT_FRONT, ",
        "SCOLORCNT_BACK, SCOLORCNT_CODE, ",
        "PART_HEIGHT, PART_WIDTH, ",
        "PART_DEPTH, FULL_HEIGHT, ",
        "FULL_WIDTH, JOIN_CNT, ",
        "PROCESS_DEMAND, PAPER_SOURCE, ",
        "PAPER_ITEM_ID, PAPER_SPEC_ID, ",
        "PAPER_WEIGHT, PAPER_TYPE, ",
        "PAPER_BRAND, PAPER_HEIGHT, ",
        "PAPER_WIDTH, CUST_SUPPLY_FLAG, ",
        "BIND_INCLUDE_FLAG, COLOR_DESC, ",
        "SCOLOR_DESC, DIFF_LEVEL, ",
        "SURFACE_DEMAND, PRINT_TYPE, ",
        "PAPER_VENDOR, PAPER_GRADE, ",
        "CALC_PAPERUSAGE, CUSTAGREE_PAPERUSAGE, ",
        "REMARK, LOCKER_ID, ",
        "LOCK_TS, MODIFYER_ID, ",
        "MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION)",
        "values (#{id,jdbcType=DECIMAL}, #{prodId,jdbcType=DECIMAL}, ",
        "#{lineNo,jdbcType=DECIMAL}, #{partType,jdbcType=NCHAR}, ",
        "#{partCode,jdbcType=NCHAR}, #{partName,jdbcType=NCHAR}, ",
        "#{pageCnt,jdbcType=DECIMAL}, #{colorcntFront,jdbcType=DECIMAL}, ",
        "#{colorcntBack,jdbcType=DECIMAL}, #{scolorcntFront,jdbcType=DECIMAL}, ",
        "#{scolorcntBack,jdbcType=DECIMAL}, #{scolorcntCode,jdbcType=DECIMAL}, ",
        "#{partHeight,jdbcType=DECIMAL}, #{partWidth,jdbcType=DECIMAL}, ",
        "#{partDepth,jdbcType=DECIMAL}, #{fullHeight,jdbcType=DECIMAL}, ",
        "#{fullWidth,jdbcType=DECIMAL}, #{joinCnt,jdbcType=DECIMAL}, ",
        "#{processDemand,jdbcType=NCHAR}, #{paperSource,jdbcType=NCHAR}, ",
        "#{paperItemId,jdbcType=DECIMAL}, #{paperSpecId,jdbcType=DECIMAL}, ",
        "#{paperWeight,jdbcType=NCHAR}, #{paperType,jdbcType=NCHAR}, ",
        "#{paperBrand,jdbcType=NCHAR}, #{paperHeight,jdbcType=DECIMAL}, ",
        "#{paperWidth,jdbcType=DECIMAL}, #{custSupplyFlag,jdbcType=DECIMAL}, ",
        "#{bindIncludeFlag,jdbcType=DECIMAL}, #{colorDesc,jdbcType=NCHAR}, ",
        "#{scolorDesc,jdbcType=NCHAR}, #{diffLevel,jdbcType=NCHAR}, ",
        "#{surfaceDemand,jdbcType=NCHAR}, #{printType,jdbcType=NCHAR}, ",
        "#{paperVendor,jdbcType=NCHAR}, #{paperGrade,jdbcType=NCHAR}, ",
        "#{calcPaperusage,jdbcType=DECIMAL}, #{custagreePaperusage,jdbcType=DECIMAL}, ",
        "#{remark,jdbcType=NCHAR}, #{lockerId,jdbcType=DECIMAL}, ",
        "#{lockTs,jdbcType=TIMESTAMP}, #{modifyerId,jdbcType=DECIMAL}, ",
        "#{modifyTs,jdbcType=TIMESTAMP}, #{modifyAppsvr,jdbcType=NCHAR}, ",
        "#{modifyModule,jdbcType=NCHAR}, #{dataVersion,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT SEQ_T_ORG_PART.NEXTVAL FROM DUAL", keyProperty="id", before=true, resultType=Long.class)
    int insert(TOrgPart record);

    @Select({
        "select",
        "ID, PROD_ID, LINE_NO, PART_TYPE, PART_CODE, PART_NAME, PAGE_CNT, COLORCNT_FRONT, ",
        "COLORCNT_BACK, SCOLORCNT_FRONT, SCOLORCNT_BACK, SCOLORCNT_CODE, PART_HEIGHT, ",
        "PART_WIDTH, PART_DEPTH, FULL_HEIGHT, FULL_WIDTH, JOIN_CNT, PROCESS_DEMAND, PAPER_SOURCE, ",
        "PAPER_ITEM_ID, PAPER_SPEC_ID, PAPER_WEIGHT, PAPER_TYPE, PAPER_BRAND, PAPER_HEIGHT, ",
        "PAPER_WIDTH, CUST_SUPPLY_FLAG, BIND_INCLUDE_FLAG, COLOR_DESC, SCOLOR_DESC, DIFF_LEVEL, ",
        "SURFACE_DEMAND, PRINT_TYPE, PAPER_VENDOR, PAPER_GRADE, CALC_PAPERUSAGE, CUSTAGREE_PAPERUSAGE, ",
        "REMARK, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, MODIFY_MODULE, ",
        "DATA_VERSION",
        "from T_ORG_PART",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PROD_ID", property="prodId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LINE_NO", property="lineNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_TYPE", property="partType", jdbcType=JdbcType.NCHAR),
        @Result(column="PART_CODE", property="partCode", jdbcType=JdbcType.NCHAR),
        @Result(column="PART_NAME", property="partName", jdbcType=JdbcType.NCHAR),
        @Result(column="PAGE_CNT", property="pageCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLORCNT_FRONT", property="colorcntFront", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLORCNT_BACK", property="colorcntBack", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_FRONT", property="scolorcntFront", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_BACK", property="scolorcntBack", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_CODE", property="scolorcntCode", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_HEIGHT", property="partHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_WIDTH", property="partWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_DEPTH", property="partDepth", jdbcType=JdbcType.DECIMAL),
        @Result(column="FULL_HEIGHT", property="fullHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="FULL_WIDTH", property="fullWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="JOIN_CNT", property="joinCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_DEMAND", property="processDemand", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_SOURCE", property="paperSource", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_ITEM_ID", property="paperItemId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_SPEC_ID", property="paperSpecId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_WEIGHT", property="paperWeight", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_TYPE", property="paperType", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_BRAND", property="paperBrand", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_HEIGHT", property="paperHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_WIDTH", property="paperWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_SUPPLY_FLAG", property="custSupplyFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_INCLUDE_FLAG", property="bindIncludeFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLOR_DESC", property="colorDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="SCOLOR_DESC", property="scolorDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DIFF_LEVEL", property="diffLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="SURFACE_DEMAND", property="surfaceDemand", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINT_TYPE", property="printType", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_VENDOR", property="paperVendor", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_GRADE", property="paperGrade", jdbcType=JdbcType.NCHAR),
        @Result(column="CALC_PAPERUSAGE", property="calcPaperusage", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUSTAGREE_PAPERUSAGE", property="custagreePaperusage", jdbcType=JdbcType.DECIMAL),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    TOrgPart selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, PROD_ID, LINE_NO, PART_TYPE, PART_CODE, PART_NAME, PAGE_CNT, COLORCNT_FRONT, ",
        "COLORCNT_BACK, SCOLORCNT_FRONT, SCOLORCNT_BACK, SCOLORCNT_CODE, PART_HEIGHT, ",
        "PART_WIDTH, PART_DEPTH, FULL_HEIGHT, FULL_WIDTH, JOIN_CNT, PROCESS_DEMAND, PAPER_SOURCE, ",
        "PAPER_ITEM_ID, PAPER_SPEC_ID, PAPER_WEIGHT, PAPER_TYPE, PAPER_BRAND, PAPER_HEIGHT, ",
        "PAPER_WIDTH, CUST_SUPPLY_FLAG, BIND_INCLUDE_FLAG, COLOR_DESC, SCOLOR_DESC, DIFF_LEVEL, ",
        "SURFACE_DEMAND, PRINT_TYPE, PAPER_VENDOR, PAPER_GRADE, CALC_PAPERUSAGE, CUSTAGREE_PAPERUSAGE, ",
        "REMARK, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, MODIFY_MODULE, ",
        "DATA_VERSION",
        "from T_ORG_PART"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PROD_ID", property="prodId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LINE_NO", property="lineNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_TYPE", property="partType", jdbcType=JdbcType.NCHAR),
        @Result(column="PART_CODE", property="partCode", jdbcType=JdbcType.NCHAR),
        @Result(column="PART_NAME", property="partName", jdbcType=JdbcType.NCHAR),
        @Result(column="PAGE_CNT", property="pageCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLORCNT_FRONT", property="colorcntFront", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLORCNT_BACK", property="colorcntBack", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_FRONT", property="scolorcntFront", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_BACK", property="scolorcntBack", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_CODE", property="scolorcntCode", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_HEIGHT", property="partHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_WIDTH", property="partWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_DEPTH", property="partDepth", jdbcType=JdbcType.DECIMAL),
        @Result(column="FULL_HEIGHT", property="fullHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="FULL_WIDTH", property="fullWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="JOIN_CNT", property="joinCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_DEMAND", property="processDemand", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_SOURCE", property="paperSource", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_ITEM_ID", property="paperItemId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_SPEC_ID", property="paperSpecId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_WEIGHT", property="paperWeight", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_TYPE", property="paperType", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_BRAND", property="paperBrand", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_HEIGHT", property="paperHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_WIDTH", property="paperWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_SUPPLY_FLAG", property="custSupplyFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_INCLUDE_FLAG", property="bindIncludeFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLOR_DESC", property="colorDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="SCOLOR_DESC", property="scolorDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DIFF_LEVEL", property="diffLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="SURFACE_DEMAND", property="surfaceDemand", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINT_TYPE", property="printType", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_VENDOR", property="paperVendor", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_GRADE", property="paperGrade", jdbcType=JdbcType.NCHAR),
        @Result(column="CALC_PAPERUSAGE", property="calcPaperusage", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUSTAGREE_PAPERUSAGE", property="custagreePaperusage", jdbcType=JdbcType.DECIMAL),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    List<TOrgPart> selectAll();

    @Update({
        "update T_ORG_PART",
        "set PROD_ID = #{prodId,jdbcType=DECIMAL},",
          "LINE_NO = #{lineNo,jdbcType=DECIMAL},",
          "PART_TYPE = #{partType,jdbcType=NCHAR},",
          "PART_CODE = #{partCode,jdbcType=NCHAR},",
          "PART_NAME = #{partName,jdbcType=NCHAR},",
          "PAGE_CNT = #{pageCnt,jdbcType=DECIMAL},",
          "COLORCNT_FRONT = #{colorcntFront,jdbcType=DECIMAL},",
          "COLORCNT_BACK = #{colorcntBack,jdbcType=DECIMAL},",
          "SCOLORCNT_FRONT = #{scolorcntFront,jdbcType=DECIMAL},",
          "SCOLORCNT_BACK = #{scolorcntBack,jdbcType=DECIMAL},",
          "SCOLORCNT_CODE = #{scolorcntCode,jdbcType=DECIMAL},",
          "PART_HEIGHT = #{partHeight,jdbcType=DECIMAL},",
          "PART_WIDTH = #{partWidth,jdbcType=DECIMAL},",
          "PART_DEPTH = #{partDepth,jdbcType=DECIMAL},",
          "FULL_HEIGHT = #{fullHeight,jdbcType=DECIMAL},",
          "FULL_WIDTH = #{fullWidth,jdbcType=DECIMAL},",
          "JOIN_CNT = #{joinCnt,jdbcType=DECIMAL},",
          "PROCESS_DEMAND = #{processDemand,jdbcType=NCHAR},",
          "PAPER_SOURCE = #{paperSource,jdbcType=NCHAR},",
          "PAPER_ITEM_ID = #{paperItemId,jdbcType=DECIMAL},",
          "PAPER_SPEC_ID = #{paperSpecId,jdbcType=DECIMAL},",
          "PAPER_WEIGHT = #{paperWeight,jdbcType=NCHAR},",
          "PAPER_TYPE = #{paperType,jdbcType=NCHAR},",
          "PAPER_BRAND = #{paperBrand,jdbcType=NCHAR},",
          "PAPER_HEIGHT = #{paperHeight,jdbcType=DECIMAL},",
          "PAPER_WIDTH = #{paperWidth,jdbcType=DECIMAL},",
          "CUST_SUPPLY_FLAG = #{custSupplyFlag,jdbcType=DECIMAL},",
          "BIND_INCLUDE_FLAG = #{bindIncludeFlag,jdbcType=DECIMAL},",
          "COLOR_DESC = #{colorDesc,jdbcType=NCHAR},",
          "SCOLOR_DESC = #{scolorDesc,jdbcType=NCHAR},",
          "DIFF_LEVEL = #{diffLevel,jdbcType=NCHAR},",
          "SURFACE_DEMAND = #{surfaceDemand,jdbcType=NCHAR},",
          "PRINT_TYPE = #{printType,jdbcType=NCHAR},",
          "PAPER_VENDOR = #{paperVendor,jdbcType=NCHAR},",
          "PAPER_GRADE = #{paperGrade,jdbcType=NCHAR},",
          "CALC_PAPERUSAGE = #{calcPaperusage,jdbcType=DECIMAL},",
          "CUSTAGREE_PAPERUSAGE = #{custagreePaperusage,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=NCHAR},",
          "LOCKER_ID = #{lockerId,jdbcType=DECIMAL},",
          "LOCK_TS = #{lockTs,jdbcType=TIMESTAMP},",
          "MODIFYER_ID = #{modifyerId,jdbcType=DECIMAL},",
          "MODIFY_TS = #{modifyTs,jdbcType=TIMESTAMP},",
          "MODIFY_APPSVR = #{modifyAppsvr,jdbcType=NCHAR},",
          "MODIFY_MODULE = #{modifyModule,jdbcType=NCHAR},",
          "DATA_VERSION = #{dataVersion,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TOrgPart record);
}