package com.el.cfg.mapper;

import com.el.cfg.domain.TOrgProd;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TOrgProdMapper {
    @Delete({
        "delete from T_ORG_PROD",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into T_ORG_PROD (ID, OU_ID, ",
        "MCU_ID, PROD_CODE, PROD_NAME, ",
        "PY, PY_ABBR, PROD_CAT1, ",
        "PROD_CAT2, PROD_UOM, PROD_FORMAT, ",
        "PROD_HEIGHT, PROD_WIDTH, ",
        "PROD_THICK, PROD_WEIGHT, ",
        "FRONT_FLAP_WIDTH, BACK_FLAP_WIDTH, ",
        "BIND_TYPE1, BIND_TYPE2, ",
        "SALE_PRICE, COLOR_STANDARD, ",
        "COLORMATCH_STANDARD, SET_FLAG, ",
        "FSC_FLAG, GREEN_FLAG, ",
        "SECRET_FLAG, SPECIAL_DEMAND, ",
        "PROD_ISBN, OPEN_TYPE, ",
        "VERSION_NUM, REPEAT_NUM, ",
        "PROD_PERIOD, PROD_BATCH, ",
        "ESTI_PRINT_QTY, WITHIN_THICK, ",
        "BOOK_NO, PREPRESS_DOC_NO, ",
        "QUALITY_LEVEL, PRINT_DIFF_LEVEL, ",
        "BIND_DIFF_LEVEL, LAST_FACT_ID, ",
        "PAGE_CNT, IMPRESSION_CNT, ",
        "SIGN_CNT, CUST_PROD_NO, ",
        "BIND_DESC, DELETE_FLAG, ",
        "VERSION_DESC, REMARK, ",
        "LOCKER_ID, LOCK_TS, ",
        "MODIFYER_ID, MODIFY_TS, ",
        "MODIFY_APPSVR, MODIFY_MODULE, ",
        "DATA_VERSION)",
        "values (#{id,jdbcType=DECIMAL}, #{ouId,jdbcType=DECIMAL}, ",
        "#{mcuId,jdbcType=DECIMAL}, #{prodCode,jdbcType=NCHAR}, #{prodName,jdbcType=NCHAR}, ",
        "#{py,jdbcType=NCHAR}, #{pyAbbr,jdbcType=NCHAR}, #{prodCat1,jdbcType=NCHAR}, ",
        "#{prodCat2,jdbcType=NCHAR}, #{prodUom,jdbcType=NCHAR}, #{prodFormat,jdbcType=NCHAR}, ",
        "#{prodHeight,jdbcType=DECIMAL}, #{prodWidth,jdbcType=DECIMAL}, ",
        "#{prodThick,jdbcType=DECIMAL}, #{prodWeight,jdbcType=DECIMAL}, ",
        "#{frontFlapWidth,jdbcType=DECIMAL}, #{backFlapWidth,jdbcType=DECIMAL}, ",
        "#{bindType1,jdbcType=NCHAR}, #{bindType2,jdbcType=NCHAR}, ",
        "#{salePrice,jdbcType=DECIMAL}, #{colorStandard,jdbcType=NCHAR}, ",
        "#{colormatchStandard,jdbcType=NCHAR}, #{setFlag,jdbcType=NCHAR}, ",
        "#{fscFlag,jdbcType=DECIMAL}, #{greenFlag,jdbcType=DECIMAL}, ",
        "#{secretFlag,jdbcType=DECIMAL}, #{specialDemand,jdbcType=NCHAR}, ",
        "#{prodIsbn,jdbcType=NCHAR}, #{openType,jdbcType=NCHAR}, ",
        "#{versionNum,jdbcType=DECIMAL}, #{repeatNum,jdbcType=DECIMAL}, ",
        "#{prodPeriod,jdbcType=NCHAR}, #{prodBatch,jdbcType=NCHAR}, ",
        "#{estiPrintQty,jdbcType=DECIMAL}, #{withinThick,jdbcType=DECIMAL}, ",
        "#{bookNo,jdbcType=NCHAR}, #{prepressDocNo,jdbcType=NCHAR}, ",
        "#{qualityLevel,jdbcType=NCHAR}, #{printDiffLevel,jdbcType=NCHAR}, ",
        "#{bindDiffLevel,jdbcType=NCHAR}, #{lastFactId,jdbcType=DECIMAL}, ",
        "#{pageCnt,jdbcType=DECIMAL}, #{impressionCnt,jdbcType=DECIMAL}, ",
        "#{signCnt,jdbcType=DECIMAL}, #{custProdNo,jdbcType=NCHAR}, ",
        "#{bindDesc,jdbcType=NCHAR}, #{deleteFlag,jdbcType=DECIMAL}, ",
        "#{versionDesc,jdbcType=NCHAR}, #{remark,jdbcType=NCHAR}, ",
        "#{lockerId,jdbcType=DECIMAL}, #{lockTs,jdbcType=TIMESTAMP}, ",
        "#{modifyerId,jdbcType=DECIMAL}, #{modifyTs,jdbcType=TIMESTAMP}, ",
        "#{modifyAppsvr,jdbcType=NCHAR}, #{modifyModule,jdbcType=NCHAR}, ",
        "#{dataVersion,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT SEQ_T_ORG_PROD.NEXTVAL FROM DUAL", keyProperty="id", before=true, resultType=Long.class)
    int insert(TOrgProd record);

    @Select({
        "select",
        "ID, OU_ID, MCU_ID, PROD_CODE, PROD_NAME, PY, PY_ABBR, PROD_CAT1, PROD_CAT2, ",
        "PROD_UOM, PROD_FORMAT, PROD_HEIGHT, PROD_WIDTH, PROD_THICK, PROD_WEIGHT, FRONT_FLAP_WIDTH, ",
        "BACK_FLAP_WIDTH, BIND_TYPE1, BIND_TYPE2, SALE_PRICE, COLOR_STANDARD, COLORMATCH_STANDARD, ",
        "SET_FLAG, FSC_FLAG, GREEN_FLAG, SECRET_FLAG, SPECIAL_DEMAND, PROD_ISBN, OPEN_TYPE, ",
        "VERSION_NUM, REPEAT_NUM, PROD_PERIOD, PROD_BATCH, ESTI_PRINT_QTY, WITHIN_THICK, ",
        "BOOK_NO, PREPRESS_DOC_NO, QUALITY_LEVEL, PRINT_DIFF_LEVEL, BIND_DIFF_LEVEL, ",
        "LAST_FACT_ID, PAGE_CNT, IMPRESSION_CNT, SIGN_CNT, CUST_PROD_NO, BIND_DESC, DELETE_FLAG, ",
        "VERSION_DESC, REMARK, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION",
        "from T_ORG_PROD",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCU_ID", property="mcuId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_CODE", property="prodCode", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_NAME", property="prodName", jdbcType=JdbcType.NCHAR),
        @Result(column="PY", property="py", jdbcType=JdbcType.NCHAR),
        @Result(column="PY_ABBR", property="pyAbbr", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_CAT1", property="prodCat1", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_CAT2", property="prodCat2", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_UOM", property="prodUom", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_FORMAT", property="prodFormat", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_HEIGHT", property="prodHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_WIDTH", property="prodWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_THICK", property="prodThick", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_WEIGHT", property="prodWeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="FRONT_FLAP_WIDTH", property="frontFlapWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="BACK_FLAP_WIDTH", property="backFlapWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_TYPE1", property="bindType1", jdbcType=JdbcType.NCHAR),
        @Result(column="BIND_TYPE2", property="bindType2", jdbcType=JdbcType.NCHAR),
        @Result(column="SALE_PRICE", property="salePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLOR_STANDARD", property="colorStandard", jdbcType=JdbcType.NCHAR),
        @Result(column="COLORMATCH_STANDARD", property="colormatchStandard", jdbcType=JdbcType.NCHAR),
        @Result(column="SET_FLAG", property="setFlag", jdbcType=JdbcType.NCHAR),
        @Result(column="FSC_FLAG", property="fscFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="GREEN_FLAG", property="greenFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SECRET_FLAG", property="secretFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPECIAL_DEMAND", property="specialDemand", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_ISBN", property="prodIsbn", jdbcType=JdbcType.NCHAR),
        @Result(column="OPEN_TYPE", property="openType", jdbcType=JdbcType.NCHAR),
        @Result(column="VERSION_NUM", property="versionNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="REPEAT_NUM", property="repeatNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_PERIOD", property="prodPeriod", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_BATCH", property="prodBatch", jdbcType=JdbcType.NCHAR),
        @Result(column="ESTI_PRINT_QTY", property="estiPrintQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="WITHIN_THICK", property="withinThick", jdbcType=JdbcType.DECIMAL),
        @Result(column="BOOK_NO", property="bookNo", jdbcType=JdbcType.NCHAR),
        @Result(column="PREPRESS_DOC_NO", property="prepressDocNo", jdbcType=JdbcType.NCHAR),
        @Result(column="QUALITY_LEVEL", property="qualityLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINT_DIFF_LEVEL", property="printDiffLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="BIND_DIFF_LEVEL", property="bindDiffLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="LAST_FACT_ID", property="lastFactId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAGE_CNT", property="pageCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMPRESSION_CNT", property="impressionCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SIGN_CNT", property="signCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_PROD_NO", property="custProdNo", jdbcType=JdbcType.NCHAR),
        @Result(column="BIND_DESC", property="bindDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DELETE_FLAG", property="deleteFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="VERSION_DESC", property="versionDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    TOrgProd selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, OU_ID, MCU_ID, PROD_CODE, PROD_NAME, PY, PY_ABBR, PROD_CAT1, PROD_CAT2, ",
        "PROD_UOM, PROD_FORMAT, PROD_HEIGHT, PROD_WIDTH, PROD_THICK, PROD_WEIGHT, FRONT_FLAP_WIDTH, ",
        "BACK_FLAP_WIDTH, BIND_TYPE1, BIND_TYPE2, SALE_PRICE, COLOR_STANDARD, COLORMATCH_STANDARD, ",
        "SET_FLAG, FSC_FLAG, GREEN_FLAG, SECRET_FLAG, SPECIAL_DEMAND, PROD_ISBN, OPEN_TYPE, ",
        "VERSION_NUM, REPEAT_NUM, PROD_PERIOD, PROD_BATCH, ESTI_PRINT_QTY, WITHIN_THICK, ",
        "BOOK_NO, PREPRESS_DOC_NO, QUALITY_LEVEL, PRINT_DIFF_LEVEL, BIND_DIFF_LEVEL, ",
        "LAST_FACT_ID, PAGE_CNT, IMPRESSION_CNT, SIGN_CNT, CUST_PROD_NO, BIND_DESC, DELETE_FLAG, ",
        "VERSION_DESC, REMARK, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION",
        "from T_ORG_PROD"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCU_ID", property="mcuId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_CODE", property="prodCode", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_NAME", property="prodName", jdbcType=JdbcType.NCHAR),
        @Result(column="PY", property="py", jdbcType=JdbcType.NCHAR),
        @Result(column="PY_ABBR", property="pyAbbr", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_CAT1", property="prodCat1", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_CAT2", property="prodCat2", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_UOM", property="prodUom", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_FORMAT", property="prodFormat", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_HEIGHT", property="prodHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_WIDTH", property="prodWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_THICK", property="prodThick", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_WEIGHT", property="prodWeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="FRONT_FLAP_WIDTH", property="frontFlapWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="BACK_FLAP_WIDTH", property="backFlapWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_TYPE1", property="bindType1", jdbcType=JdbcType.NCHAR),
        @Result(column="BIND_TYPE2", property="bindType2", jdbcType=JdbcType.NCHAR),
        @Result(column="SALE_PRICE", property="salePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLOR_STANDARD", property="colorStandard", jdbcType=JdbcType.NCHAR),
        @Result(column="COLORMATCH_STANDARD", property="colormatchStandard", jdbcType=JdbcType.NCHAR),
        @Result(column="SET_FLAG", property="setFlag", jdbcType=JdbcType.NCHAR),
        @Result(column="FSC_FLAG", property="fscFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="GREEN_FLAG", property="greenFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SECRET_FLAG", property="secretFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPECIAL_DEMAND", property="specialDemand", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_ISBN", property="prodIsbn", jdbcType=JdbcType.NCHAR),
        @Result(column="OPEN_TYPE", property="openType", jdbcType=JdbcType.NCHAR),
        @Result(column="VERSION_NUM", property="versionNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="REPEAT_NUM", property="repeatNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_PERIOD", property="prodPeriod", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_BATCH", property="prodBatch", jdbcType=JdbcType.NCHAR),
        @Result(column="ESTI_PRINT_QTY", property="estiPrintQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="WITHIN_THICK", property="withinThick", jdbcType=JdbcType.DECIMAL),
        @Result(column="BOOK_NO", property="bookNo", jdbcType=JdbcType.NCHAR),
        @Result(column="PREPRESS_DOC_NO", property="prepressDocNo", jdbcType=JdbcType.NCHAR),
        @Result(column="QUALITY_LEVEL", property="qualityLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINT_DIFF_LEVEL", property="printDiffLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="BIND_DIFF_LEVEL", property="bindDiffLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="LAST_FACT_ID", property="lastFactId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAGE_CNT", property="pageCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="IMPRESSION_CNT", property="impressionCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SIGN_CNT", property="signCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_PROD_NO", property="custProdNo", jdbcType=JdbcType.NCHAR),
        @Result(column="BIND_DESC", property="bindDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DELETE_FLAG", property="deleteFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="VERSION_DESC", property="versionDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    List<TOrgProd> selectAll();

    @Update({
        "update T_ORG_PROD",
        "set OU_ID = #{ouId,jdbcType=DECIMAL},",
          "MCU_ID = #{mcuId,jdbcType=DECIMAL},",
          "PROD_CODE = #{prodCode,jdbcType=NCHAR},",
          "PROD_NAME = #{prodName,jdbcType=NCHAR},",
          "PY = #{py,jdbcType=NCHAR},",
          "PY_ABBR = #{pyAbbr,jdbcType=NCHAR},",
          "PROD_CAT1 = #{prodCat1,jdbcType=NCHAR},",
          "PROD_CAT2 = #{prodCat2,jdbcType=NCHAR},",
          "PROD_UOM = #{prodUom,jdbcType=NCHAR},",
          "PROD_FORMAT = #{prodFormat,jdbcType=NCHAR},",
          "PROD_HEIGHT = #{prodHeight,jdbcType=DECIMAL},",
          "PROD_WIDTH = #{prodWidth,jdbcType=DECIMAL},",
          "PROD_THICK = #{prodThick,jdbcType=DECIMAL},",
          "PROD_WEIGHT = #{prodWeight,jdbcType=DECIMAL},",
          "FRONT_FLAP_WIDTH = #{frontFlapWidth,jdbcType=DECIMAL},",
          "BACK_FLAP_WIDTH = #{backFlapWidth,jdbcType=DECIMAL},",
          "BIND_TYPE1 = #{bindType1,jdbcType=NCHAR},",
          "BIND_TYPE2 = #{bindType2,jdbcType=NCHAR},",
          "SALE_PRICE = #{salePrice,jdbcType=DECIMAL},",
          "COLOR_STANDARD = #{colorStandard,jdbcType=NCHAR},",
          "COLORMATCH_STANDARD = #{colormatchStandard,jdbcType=NCHAR},",
          "SET_FLAG = #{setFlag,jdbcType=NCHAR},",
          "FSC_FLAG = #{fscFlag,jdbcType=DECIMAL},",
          "GREEN_FLAG = #{greenFlag,jdbcType=DECIMAL},",
          "SECRET_FLAG = #{secretFlag,jdbcType=DECIMAL},",
          "SPECIAL_DEMAND = #{specialDemand,jdbcType=NCHAR},",
          "PROD_ISBN = #{prodIsbn,jdbcType=NCHAR},",
          "OPEN_TYPE = #{openType,jdbcType=NCHAR},",
          "VERSION_NUM = #{versionNum,jdbcType=DECIMAL},",
          "REPEAT_NUM = #{repeatNum,jdbcType=DECIMAL},",
          "PROD_PERIOD = #{prodPeriod,jdbcType=NCHAR},",
          "PROD_BATCH = #{prodBatch,jdbcType=NCHAR},",
          "ESTI_PRINT_QTY = #{estiPrintQty,jdbcType=DECIMAL},",
          "WITHIN_THICK = #{withinThick,jdbcType=DECIMAL},",
          "BOOK_NO = #{bookNo,jdbcType=NCHAR},",
          "PREPRESS_DOC_NO = #{prepressDocNo,jdbcType=NCHAR},",
          "QUALITY_LEVEL = #{qualityLevel,jdbcType=NCHAR},",
          "PRINT_DIFF_LEVEL = #{printDiffLevel,jdbcType=NCHAR},",
          "BIND_DIFF_LEVEL = #{bindDiffLevel,jdbcType=NCHAR},",
          "LAST_FACT_ID = #{lastFactId,jdbcType=DECIMAL},",
          "PAGE_CNT = #{pageCnt,jdbcType=DECIMAL},",
          "IMPRESSION_CNT = #{impressionCnt,jdbcType=DECIMAL},",
          "SIGN_CNT = #{signCnt,jdbcType=DECIMAL},",
          "CUST_PROD_NO = #{custProdNo,jdbcType=NCHAR},",
          "BIND_DESC = #{bindDesc,jdbcType=NCHAR},",
          "DELETE_FLAG = #{deleteFlag,jdbcType=DECIMAL},",
          "VERSION_DESC = #{versionDesc,jdbcType=NCHAR},",
          "REMARK = #{remark,jdbcType=NCHAR},",
          "LOCKER_ID = #{lockerId,jdbcType=DECIMAL},",
          "LOCK_TS = #{lockTs,jdbcType=TIMESTAMP},",
          "MODIFYER_ID = #{modifyerId,jdbcType=DECIMAL},",
          "MODIFY_TS = #{modifyTs,jdbcType=TIMESTAMP},",
          "MODIFY_APPSVR = #{modifyAppsvr,jdbcType=NCHAR},",
          "MODIFY_MODULE = #{modifyModule,jdbcType=NCHAR},",
          "DATA_VERSION = #{dataVersion,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TOrgProd record);
}