package com.el.cfg.mapper;

import com.el.cfg.domain.TProdProcess;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TProdProcessMapper {
    @Delete({
        "delete from T_PROD_PROCESS",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into T_PROD_PROCESS (ID, PROD_ID, ",
        "PART_ID, PART_NAME, ",
        "PRODROUTE_ID, ROUTE_DESC, ",
        "PROCESS_ID, PROCESS_SORTNO, ",
        "PROCESS_CODE, NEXT_SORT_NO, ",
        "MACHINE_TYPE, MANU_NO, ",
        "PAGE_CNT, SIGN_CNT, ",
        "PAGE_DESC, PAGECNT_PER_SIGN, ",
        "SETS_CNT, SETS_METHOD, ",
        "PRINT_METHOD, COLORCNT_FRONT, ",
        "COLORCNT_BACK, SCOLORCNT_FRONT, ",
        "SCOLORCNT_BACK, COLOR_DESC, ",
        "SCOLOR_DESC, UNIONVANISH, ",
        "UNIONVANISH_FACES, UNIONVANISH_PLATECNT, ",
        "PAPER_FORMAT, PRINTPAPER_HEIGHT, ",
        "PRINTPAPER_WIDTH, MATERIAL_SOURCE, ",
        "MATERIAL_ID, MATERIAL_QTY, ",
        "MATERIAL_UOM, PLATE_TYPE, ",
        "PLATECNT_PER_SIGN, PLATE_CNT, ",
        "PLATE_SETCNT, SCREEN_TYPE, ",
        "SCREEN_DPI, MANU_QTY, ",
        "PRINT_ADDUP, BIND_ADDUP, ",
        "REAM_PER_SIGN, REAM_CNT, ",
        "PAPER_USAGE, CUSTAGREE_USAGE, ",
        "PAPER_UTILIZE_RATIO, DIFF_LEVEL, ",
        "INKQTY_DESC, PROCESS_AREA, ",
        "PROCESS_UOM, PROCESS_QTY, ",
        "PROCESS_FORMAT, PROCESS_DEMAND, ",
        "PROCESS_DESC, AFTERPROCESS_PAGEPERSIGN, ",
        "FLAP_SIZE, MOLD_CNT, ",
        "MOLD_AMT, SAMPLE, REMARK, ",
        "LOCKER_ID, LOCK_TS, ",
        "MODIFYER_ID, MODIFY_TS, ",
        "MODIFY_APPSVR, MODIFY_MODULE, ",
        "DATA_VERSION)",
        "values (#{id,jdbcType=DECIMAL}, #{prodId,jdbcType=DECIMAL}, ",
        "#{partId,jdbcType=DECIMAL}, #{partName,jdbcType=NCHAR}, ",
        "#{prodrouteId,jdbcType=DECIMAL}, #{routeDesc,jdbcType=NCHAR}, ",
        "#{processId,jdbcType=DECIMAL}, #{processSortno,jdbcType=DECIMAL}, ",
        "#{processCode,jdbcType=NCHAR}, #{nextSortNo,jdbcType=DECIMAL}, ",
        "#{machineType,jdbcType=NCHAR}, #{manuNo,jdbcType=NCHAR}, ",
        "#{pageCnt,jdbcType=DECIMAL}, #{signCnt,jdbcType=DECIMAL}, ",
        "#{pageDesc,jdbcType=NCHAR}, #{pagecntPerSign,jdbcType=DECIMAL}, ",
        "#{setsCnt,jdbcType=DECIMAL}, #{setsMethod,jdbcType=NCHAR}, ",
        "#{printMethod,jdbcType=NCHAR}, #{colorcntFront,jdbcType=DECIMAL}, ",
        "#{colorcntBack,jdbcType=DECIMAL}, #{scolorcntFront,jdbcType=DECIMAL}, ",
        "#{scolorcntBack,jdbcType=DECIMAL}, #{colorDesc,jdbcType=NCHAR}, ",
        "#{scolorDesc,jdbcType=NCHAR}, #{unionvanish,jdbcType=NCHAR}, ",
        "#{unionvanishFaces,jdbcType=NCHAR}, #{unionvanishPlatecnt,jdbcType=DECIMAL}, ",
        "#{paperFormat,jdbcType=NCHAR}, #{printpaperHeight,jdbcType=DECIMAL}, ",
        "#{printpaperWidth,jdbcType=DECIMAL}, #{materialSource,jdbcType=NCHAR}, ",
        "#{materialId,jdbcType=DECIMAL}, #{materialQty,jdbcType=DECIMAL}, ",
        "#{materialUom,jdbcType=NCHAR}, #{plateType,jdbcType=NCHAR}, ",
        "#{platecntPerSign,jdbcType=DECIMAL}, #{plateCnt,jdbcType=DECIMAL}, ",
        "#{plateSetcnt,jdbcType=DECIMAL}, #{screenType,jdbcType=NCHAR}, ",
        "#{screenDpi,jdbcType=NCHAR}, #{manuQty,jdbcType=DECIMAL}, ",
        "#{printAddup,jdbcType=DECIMAL}, #{bindAddup,jdbcType=DECIMAL}, ",
        "#{reamPerSign,jdbcType=DECIMAL}, #{reamCnt,jdbcType=DECIMAL}, ",
        "#{paperUsage,jdbcType=DECIMAL}, #{custagreeUsage,jdbcType=DECIMAL}, ",
        "#{paperUtilizeRatio,jdbcType=DECIMAL}, #{diffLevel,jdbcType=NCHAR}, ",
        "#{inkqtyDesc,jdbcType=NCHAR}, #{processArea,jdbcType=DECIMAL}, ",
        "#{processUom,jdbcType=NCHAR}, #{processQty,jdbcType=DECIMAL}, ",
        "#{processFormat,jdbcType=NCHAR}, #{processDemand,jdbcType=NCHAR}, ",
        "#{processDesc,jdbcType=NCHAR}, #{afterprocessPagepersign,jdbcType=DECIMAL}, ",
        "#{flapSize,jdbcType=DECIMAL}, #{moldCnt,jdbcType=DECIMAL}, ",
        "#{moldAmt,jdbcType=DECIMAL}, #{sample,jdbcType=NCHAR}, #{remark,jdbcType=NCHAR}, ",
        "#{lockerId,jdbcType=DECIMAL}, #{lockTs,jdbcType=TIMESTAMP}, ",
        "#{modifyerId,jdbcType=DECIMAL}, #{modifyTs,jdbcType=TIMESTAMP}, ",
        "#{modifyAppsvr,jdbcType=NCHAR}, #{modifyModule,jdbcType=NCHAR}, ",
        "#{dataVersion,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT SEQ_T_PROD_PROCESS.NEXTVAL FROM DUAL", keyProperty="id", before=true, resultType=Long.class)
    int insert(TProdProcess record);

    @Select({
        "select",
        "ID, PROD_ID, PART_ID, PART_NAME, PRODROUTE_ID, ROUTE_DESC, PROCESS_ID, PROCESS_SORTNO, ",
        "PROCESS_CODE, NEXT_SORT_NO, MACHINE_TYPE, MANU_NO, PAGE_CNT, SIGN_CNT, PAGE_DESC, ",
        "PAGECNT_PER_SIGN, SETS_CNT, SETS_METHOD, PRINT_METHOD, COLORCNT_FRONT, COLORCNT_BACK, ",
        "SCOLORCNT_FRONT, SCOLORCNT_BACK, COLOR_DESC, SCOLOR_DESC, UNIONVANISH, UNIONVANISH_FACES, ",
        "UNIONVANISH_PLATECNT, PAPER_FORMAT, PRINTPAPER_HEIGHT, PRINTPAPER_WIDTH, MATERIAL_SOURCE, ",
        "MATERIAL_ID, MATERIAL_QTY, MATERIAL_UOM, PLATE_TYPE, PLATECNT_PER_SIGN, PLATE_CNT, ",
        "PLATE_SETCNT, SCREEN_TYPE, SCREEN_DPI, MANU_QTY, PRINT_ADDUP, BIND_ADDUP, REAM_PER_SIGN, ",
        "REAM_CNT, PAPER_USAGE, CUSTAGREE_USAGE, PAPER_UTILIZE_RATIO, DIFF_LEVEL, INKQTY_DESC, ",
        "PROCESS_AREA, PROCESS_UOM, PROCESS_QTY, PROCESS_FORMAT, PROCESS_DEMAND, PROCESS_DESC, ",
        "AFTERPROCESS_PAGEPERSIGN, FLAP_SIZE, MOLD_CNT, MOLD_AMT, SAMPLE, REMARK, LOCKER_ID, ",
        "LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, MODIFY_MODULE, DATA_VERSION",
        "from T_PROD_PROCESS",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PROD_ID", property="prodId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_ID", property="partId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_NAME", property="partName", jdbcType=JdbcType.NCHAR),
        @Result(column="PRODROUTE_ID", property="prodrouteId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ROUTE_DESC", property="routeDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_ID", property="processId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_SORTNO", property="processSortno", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_CODE", property="processCode", jdbcType=JdbcType.NCHAR),
        @Result(column="NEXT_SORT_NO", property="nextSortNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="MACHINE_TYPE", property="machineType", jdbcType=JdbcType.NCHAR),
        @Result(column="MANU_NO", property="manuNo", jdbcType=JdbcType.NCHAR),
        @Result(column="PAGE_CNT", property="pageCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SIGN_CNT", property="signCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAGE_DESC", property="pageDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="PAGECNT_PER_SIGN", property="pagecntPerSign", jdbcType=JdbcType.DECIMAL),
        @Result(column="SETS_CNT", property="setsCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SETS_METHOD", property="setsMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINT_METHOD", property="printMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="COLORCNT_FRONT", property="colorcntFront", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLORCNT_BACK", property="colorcntBack", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_FRONT", property="scolorcntFront", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_BACK", property="scolorcntBack", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLOR_DESC", property="colorDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="SCOLOR_DESC", property="scolorDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="UNIONVANISH", property="unionvanish", jdbcType=JdbcType.NCHAR),
        @Result(column="UNIONVANISH_FACES", property="unionvanishFaces", jdbcType=JdbcType.NCHAR),
        @Result(column="UNIONVANISH_PLATECNT", property="unionvanishPlatecnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_FORMAT", property="paperFormat", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINTPAPER_HEIGHT", property="printpaperHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRINTPAPER_WIDTH", property="printpaperWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="MATERIAL_SOURCE", property="materialSource", jdbcType=JdbcType.NCHAR),
        @Result(column="MATERIAL_ID", property="materialId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MATERIAL_QTY", property="materialQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="MATERIAL_UOM", property="materialUom", jdbcType=JdbcType.NCHAR),
        @Result(column="PLATE_TYPE", property="plateType", jdbcType=JdbcType.NCHAR),
        @Result(column="PLATECNT_PER_SIGN", property="platecntPerSign", jdbcType=JdbcType.DECIMAL),
        @Result(column="PLATE_CNT", property="plateCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PLATE_SETCNT", property="plateSetcnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCREEN_TYPE", property="screenType", jdbcType=JdbcType.NCHAR),
        @Result(column="SCREEN_DPI", property="screenDpi", jdbcType=JdbcType.NCHAR),
        @Result(column="MANU_QTY", property="manuQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRINT_ADDUP", property="printAddup", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_ADDUP", property="bindAddup", jdbcType=JdbcType.DECIMAL),
        @Result(column="REAM_PER_SIGN", property="reamPerSign", jdbcType=JdbcType.DECIMAL),
        @Result(column="REAM_CNT", property="reamCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_USAGE", property="paperUsage", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUSTAGREE_USAGE", property="custagreeUsage", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_UTILIZE_RATIO", property="paperUtilizeRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIFF_LEVEL", property="diffLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="INKQTY_DESC", property="inkqtyDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_AREA", property="processArea", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_UOM", property="processUom", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_QTY", property="processQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_FORMAT", property="processFormat", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_DEMAND", property="processDemand", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_DESC", property="processDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="AFTERPROCESS_PAGEPERSIGN", property="afterprocessPagepersign", jdbcType=JdbcType.DECIMAL),
        @Result(column="FLAP_SIZE", property="flapSize", jdbcType=JdbcType.DECIMAL),
        @Result(column="MOLD_CNT", property="moldCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="MOLD_AMT", property="moldAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SAMPLE", property="sample", jdbcType=JdbcType.NCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    TProdProcess selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, PROD_ID, PART_ID, PART_NAME, PRODROUTE_ID, ROUTE_DESC, PROCESS_ID, PROCESS_SORTNO, ",
        "PROCESS_CODE, NEXT_SORT_NO, MACHINE_TYPE, MANU_NO, PAGE_CNT, SIGN_CNT, PAGE_DESC, ",
        "PAGECNT_PER_SIGN, SETS_CNT, SETS_METHOD, PRINT_METHOD, COLORCNT_FRONT, COLORCNT_BACK, ",
        "SCOLORCNT_FRONT, SCOLORCNT_BACK, COLOR_DESC, SCOLOR_DESC, UNIONVANISH, UNIONVANISH_FACES, ",
        "UNIONVANISH_PLATECNT, PAPER_FORMAT, PRINTPAPER_HEIGHT, PRINTPAPER_WIDTH, MATERIAL_SOURCE, ",
        "MATERIAL_ID, MATERIAL_QTY, MATERIAL_UOM, PLATE_TYPE, PLATECNT_PER_SIGN, PLATE_CNT, ",
        "PLATE_SETCNT, SCREEN_TYPE, SCREEN_DPI, MANU_QTY, PRINT_ADDUP, BIND_ADDUP, REAM_PER_SIGN, ",
        "REAM_CNT, PAPER_USAGE, CUSTAGREE_USAGE, PAPER_UTILIZE_RATIO, DIFF_LEVEL, INKQTY_DESC, ",
        "PROCESS_AREA, PROCESS_UOM, PROCESS_QTY, PROCESS_FORMAT, PROCESS_DEMAND, PROCESS_DESC, ",
        "AFTERPROCESS_PAGEPERSIGN, FLAP_SIZE, MOLD_CNT, MOLD_AMT, SAMPLE, REMARK, LOCKER_ID, ",
        "LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, MODIFY_MODULE, DATA_VERSION",
        "from T_PROD_PROCESS"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="PROD_ID", property="prodId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_ID", property="partId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PART_NAME", property="partName", jdbcType=JdbcType.NCHAR),
        @Result(column="PRODROUTE_ID", property="prodrouteId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ROUTE_DESC", property="routeDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_ID", property="processId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_SORTNO", property="processSortno", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_CODE", property="processCode", jdbcType=JdbcType.NCHAR),
        @Result(column="NEXT_SORT_NO", property="nextSortNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="MACHINE_TYPE", property="machineType", jdbcType=JdbcType.NCHAR),
        @Result(column="MANU_NO", property="manuNo", jdbcType=JdbcType.NCHAR),
        @Result(column="PAGE_CNT", property="pageCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SIGN_CNT", property="signCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAGE_DESC", property="pageDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="PAGECNT_PER_SIGN", property="pagecntPerSign", jdbcType=JdbcType.DECIMAL),
        @Result(column="SETS_CNT", property="setsCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SETS_METHOD", property="setsMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINT_METHOD", property="printMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="COLORCNT_FRONT", property="colorcntFront", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLORCNT_BACK", property="colorcntBack", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_FRONT", property="scolorcntFront", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCOLORCNT_BACK", property="scolorcntBack", jdbcType=JdbcType.DECIMAL),
        @Result(column="COLOR_DESC", property="colorDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="SCOLOR_DESC", property="scolorDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="UNIONVANISH", property="unionvanish", jdbcType=JdbcType.NCHAR),
        @Result(column="UNIONVANISH_FACES", property="unionvanishFaces", jdbcType=JdbcType.NCHAR),
        @Result(column="UNIONVANISH_PLATECNT", property="unionvanishPlatecnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_FORMAT", property="paperFormat", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINTPAPER_HEIGHT", property="printpaperHeight", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRINTPAPER_WIDTH", property="printpaperWidth", jdbcType=JdbcType.DECIMAL),
        @Result(column="MATERIAL_SOURCE", property="materialSource", jdbcType=JdbcType.NCHAR),
        @Result(column="MATERIAL_ID", property="materialId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MATERIAL_QTY", property="materialQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="MATERIAL_UOM", property="materialUom", jdbcType=JdbcType.NCHAR),
        @Result(column="PLATE_TYPE", property="plateType", jdbcType=JdbcType.NCHAR),
        @Result(column="PLATECNT_PER_SIGN", property="platecntPerSign", jdbcType=JdbcType.DECIMAL),
        @Result(column="PLATE_CNT", property="plateCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PLATE_SETCNT", property="plateSetcnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SCREEN_TYPE", property="screenType", jdbcType=JdbcType.NCHAR),
        @Result(column="SCREEN_DPI", property="screenDpi", jdbcType=JdbcType.NCHAR),
        @Result(column="MANU_QTY", property="manuQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRINT_ADDUP", property="printAddup", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_ADDUP", property="bindAddup", jdbcType=JdbcType.DECIMAL),
        @Result(column="REAM_PER_SIGN", property="reamPerSign", jdbcType=JdbcType.DECIMAL),
        @Result(column="REAM_CNT", property="reamCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_USAGE", property="paperUsage", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUSTAGREE_USAGE", property="custagreeUsage", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAPER_UTILIZE_RATIO", property="paperUtilizeRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIFF_LEVEL", property="diffLevel", jdbcType=JdbcType.NCHAR),
        @Result(column="INKQTY_DESC", property="inkqtyDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_AREA", property="processArea", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_UOM", property="processUom", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_QTY", property="processQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROCESS_FORMAT", property="processFormat", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_DEMAND", property="processDemand", jdbcType=JdbcType.NCHAR),
        @Result(column="PROCESS_DESC", property="processDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="AFTERPROCESS_PAGEPERSIGN", property="afterprocessPagepersign", jdbcType=JdbcType.DECIMAL),
        @Result(column="FLAP_SIZE", property="flapSize", jdbcType=JdbcType.DECIMAL),
        @Result(column="MOLD_CNT", property="moldCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="MOLD_AMT", property="moldAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SAMPLE", property="sample", jdbcType=JdbcType.NCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    List<TProdProcess> selectAll();

    @Update({
        "update T_PROD_PROCESS",
        "set PROD_ID = #{prodId,jdbcType=DECIMAL},",
          "PART_ID = #{partId,jdbcType=DECIMAL},",
          "PART_NAME = #{partName,jdbcType=NCHAR},",
          "PRODROUTE_ID = #{prodrouteId,jdbcType=DECIMAL},",
          "ROUTE_DESC = #{routeDesc,jdbcType=NCHAR},",
          "PROCESS_ID = #{processId,jdbcType=DECIMAL},",
          "PROCESS_SORTNO = #{processSortno,jdbcType=DECIMAL},",
          "PROCESS_CODE = #{processCode,jdbcType=NCHAR},",
          "NEXT_SORT_NO = #{nextSortNo,jdbcType=DECIMAL},",
          "MACHINE_TYPE = #{machineType,jdbcType=NCHAR},",
          "MANU_NO = #{manuNo,jdbcType=NCHAR},",
          "PAGE_CNT = #{pageCnt,jdbcType=DECIMAL},",
          "SIGN_CNT = #{signCnt,jdbcType=DECIMAL},",
          "PAGE_DESC = #{pageDesc,jdbcType=NCHAR},",
          "PAGECNT_PER_SIGN = #{pagecntPerSign,jdbcType=DECIMAL},",
          "SETS_CNT = #{setsCnt,jdbcType=DECIMAL},",
          "SETS_METHOD = #{setsMethod,jdbcType=NCHAR},",
          "PRINT_METHOD = #{printMethod,jdbcType=NCHAR},",
          "COLORCNT_FRONT = #{colorcntFront,jdbcType=DECIMAL},",
          "COLORCNT_BACK = #{colorcntBack,jdbcType=DECIMAL},",
          "SCOLORCNT_FRONT = #{scolorcntFront,jdbcType=DECIMAL},",
          "SCOLORCNT_BACK = #{scolorcntBack,jdbcType=DECIMAL},",
          "COLOR_DESC = #{colorDesc,jdbcType=NCHAR},",
          "SCOLOR_DESC = #{scolorDesc,jdbcType=NCHAR},",
          "UNIONVANISH = #{unionvanish,jdbcType=NCHAR},",
          "UNIONVANISH_FACES = #{unionvanishFaces,jdbcType=NCHAR},",
          "UNIONVANISH_PLATECNT = #{unionvanishPlatecnt,jdbcType=DECIMAL},",
          "PAPER_FORMAT = #{paperFormat,jdbcType=NCHAR},",
          "PRINTPAPER_HEIGHT = #{printpaperHeight,jdbcType=DECIMAL},",
          "PRINTPAPER_WIDTH = #{printpaperWidth,jdbcType=DECIMAL},",
          "MATERIAL_SOURCE = #{materialSource,jdbcType=NCHAR},",
          "MATERIAL_ID = #{materialId,jdbcType=DECIMAL},",
          "MATERIAL_QTY = #{materialQty,jdbcType=DECIMAL},",
          "MATERIAL_UOM = #{materialUom,jdbcType=NCHAR},",
          "PLATE_TYPE = #{plateType,jdbcType=NCHAR},",
          "PLATECNT_PER_SIGN = #{platecntPerSign,jdbcType=DECIMAL},",
          "PLATE_CNT = #{plateCnt,jdbcType=DECIMAL},",
          "PLATE_SETCNT = #{plateSetcnt,jdbcType=DECIMAL},",
          "SCREEN_TYPE = #{screenType,jdbcType=NCHAR},",
          "SCREEN_DPI = #{screenDpi,jdbcType=NCHAR},",
          "MANU_QTY = #{manuQty,jdbcType=DECIMAL},",
          "PRINT_ADDUP = #{printAddup,jdbcType=DECIMAL},",
          "BIND_ADDUP = #{bindAddup,jdbcType=DECIMAL},",
          "REAM_PER_SIGN = #{reamPerSign,jdbcType=DECIMAL},",
          "REAM_CNT = #{reamCnt,jdbcType=DECIMAL},",
          "PAPER_USAGE = #{paperUsage,jdbcType=DECIMAL},",
          "CUSTAGREE_USAGE = #{custagreeUsage,jdbcType=DECIMAL},",
          "PAPER_UTILIZE_RATIO = #{paperUtilizeRatio,jdbcType=DECIMAL},",
          "DIFF_LEVEL = #{diffLevel,jdbcType=NCHAR},",
          "INKQTY_DESC = #{inkqtyDesc,jdbcType=NCHAR},",
          "PROCESS_AREA = #{processArea,jdbcType=DECIMAL},",
          "PROCESS_UOM = #{processUom,jdbcType=NCHAR},",
          "PROCESS_QTY = #{processQty,jdbcType=DECIMAL},",
          "PROCESS_FORMAT = #{processFormat,jdbcType=NCHAR},",
          "PROCESS_DEMAND = #{processDemand,jdbcType=NCHAR},",
          "PROCESS_DESC = #{processDesc,jdbcType=NCHAR},",
          "AFTERPROCESS_PAGEPERSIGN = #{afterprocessPagepersign,jdbcType=DECIMAL},",
          "FLAP_SIZE = #{flapSize,jdbcType=DECIMAL},",
          "MOLD_CNT = #{moldCnt,jdbcType=DECIMAL},",
          "MOLD_AMT = #{moldAmt,jdbcType=DECIMAL},",
          "SAMPLE = #{sample,jdbcType=NCHAR},",
          "REMARK = #{remark,jdbcType=NCHAR},",
          "LOCKER_ID = #{lockerId,jdbcType=DECIMAL},",
          "LOCK_TS = #{lockTs,jdbcType=TIMESTAMP},",
          "MODIFYER_ID = #{modifyerId,jdbcType=DECIMAL},",
          "MODIFY_TS = #{modifyTs,jdbcType=TIMESTAMP},",
          "MODIFY_APPSVR = #{modifyAppsvr,jdbcType=NCHAR},",
          "MODIFY_MODULE = #{modifyModule,jdbcType=NCHAR},",
          "DATA_VERSION = #{dataVersion,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TProdProcess record);
}