package com.el.cfg.mapper;

import com.el.cfg.domain.TQuoteProd;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TQuoteProdMapper {
    @Delete({
        "delete from T_QUOTE_PROD",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into T_QUOTE_PROD (ID, QUOTE_ID, ",
        "LINE_NO, LINE_TYPE, ",
        "PROD_ID, CHANGE_FLAG, ",
        "VERSION_NUM, REPEAT_NUM, ",
        "QUOTE_STATUS, DIST_STATUS, ",
        "SETTLE_STATUS, CREDIT_STATUS, ",
        "HOME_CURR_CODE, FORE_CURR_CODE, ",
        "CURR_RATE, CALC_PRICE, ",
        "CURR_CALC_PRICE, QUOTE_PRICE, ",
        "CURR_QUOTE_PRICE, CALC_AMT, ",
        "CURR_CALC_AMT, QUOTE_AMT, ",
        "CURR_QUOTE_AMT, CUST_AMT, ",
        "CURR_CUST_AMT, FORFREE_QTY, ",
        "FORCHECK_QTY, FORKEEP_QTY, ",
        "FORCUSTSAMPLE_QTY, MANU_QTY, ",
        "FREE_FLAG, PROD_UOM, ",
        "DISTING_QTY, DIST_QTY, ",
        "QTY_SPLIT_FLAG, SAMPLE_TYPE, ",
        "PACKAGE_TYPE, MANU_PACK_TYPE, ",
        "DUE_DATE, DELI_ADDR_ID, ",
        "DELI_ADDR_DESC, DELI_METHOD, ",
        "IMPRESSION_CNT, PRINT_COMP_CNT, ",
        "BIND_COMP_CNT, MANU_COMP_DATE, ",
        "WHIN_QTY, DELI_QTY, ",
        "LAST_DELI_DATE, SETTLE_FLAG, ",
        "SETTLE_QTY, SETTLE_AMT, ",
        "CURR_SETTLE_AMT, INV_AMT, ",
        "RECV_AMT, WH_ID, CANCLE_DATE, ",
        "PAPER_READY_FLAG, REMARK, ",
        "LOCKER_ID, LOCK_TS, ",
        "MODIFYER_ID, MODIFY_TS, ",
        "MODIFY_APPSVR, MODIFY_MODULE, ",
        "DATA_VERSION)",
        "values (#{id,jdbcType=DECIMAL}, #{quoteId,jdbcType=DECIMAL}, ",
        "#{lineNo,jdbcType=DECIMAL}, #{lineType,jdbcType=NCHAR}, ",
        "#{prodId,jdbcType=DECIMAL}, #{changeFlag,jdbcType=NCHAR}, ",
        "#{versionNum,jdbcType=DECIMAL}, #{repeatNum,jdbcType=DECIMAL}, ",
        "#{quoteStatus,jdbcType=NCHAR}, #{distStatus,jdbcType=NCHAR}, ",
        "#{settleStatus,jdbcType=NCHAR}, #{creditStatus,jdbcType=NCHAR}, ",
        "#{homeCurrCode,jdbcType=NCHAR}, #{foreCurrCode,jdbcType=NCHAR}, ",
        "#{currRate,jdbcType=DECIMAL}, #{calcPrice,jdbcType=DECIMAL}, ",
        "#{currCalcPrice,jdbcType=DECIMAL}, #{quotePrice,jdbcType=DECIMAL}, ",
        "#{currQuotePrice,jdbcType=DECIMAL}, #{calcAmt,jdbcType=DECIMAL}, ",
        "#{currCalcAmt,jdbcType=DECIMAL}, #{quoteAmt,jdbcType=DECIMAL}, ",
        "#{currQuoteAmt,jdbcType=DECIMAL}, #{custAmt,jdbcType=DECIMAL}, ",
        "#{currCustAmt,jdbcType=DECIMAL}, #{forfreeQty,jdbcType=DECIMAL}, ",
        "#{forcheckQty,jdbcType=DECIMAL}, #{forkeepQty,jdbcType=DECIMAL}, ",
        "#{forcustsampleQty,jdbcType=DECIMAL}, #{manuQty,jdbcType=DECIMAL}, ",
        "#{freeFlag,jdbcType=DECIMAL}, #{prodUom,jdbcType=NCHAR}, ",
        "#{distingQty,jdbcType=DECIMAL}, #{distQty,jdbcType=DECIMAL}, ",
        "#{qtySplitFlag,jdbcType=DECIMAL}, #{sampleType,jdbcType=NCHAR}, ",
        "#{packageType,jdbcType=NCHAR}, #{manuPackType,jdbcType=NCHAR}, ",
        "#{dueDate,jdbcType=TIMESTAMP}, #{deliAddrId,jdbcType=DECIMAL}, ",
        "#{deliAddrDesc,jdbcType=NCHAR}, #{deliMethod,jdbcType=NCHAR}, ",
        "#{impressionCnt,jdbcType=DECIMAL}, #{printCompCnt,jdbcType=DECIMAL}, ",
        "#{bindCompCnt,jdbcType=DECIMAL}, #{manuCompDate,jdbcType=TIMESTAMP}, ",
        "#{whinQty,jdbcType=DECIMAL}, #{deliQty,jdbcType=DECIMAL}, ",
        "#{lastDeliDate,jdbcType=TIMESTAMP}, #{settleFlag,jdbcType=NCHAR}, ",
        "#{settleQty,jdbcType=DECIMAL}, #{settleAmt,jdbcType=DECIMAL}, ",
        "#{currSettleAmt,jdbcType=DECIMAL}, #{invAmt,jdbcType=DECIMAL}, ",
        "#{recvAmt,jdbcType=DECIMAL}, #{whId,jdbcType=DECIMAL}, #{cancleDate,jdbcType=TIMESTAMP}, ",
        "#{paperReadyFlag,jdbcType=DECIMAL}, #{remark,jdbcType=NCHAR}, ",
        "#{lockerId,jdbcType=DECIMAL}, #{lockTs,jdbcType=TIMESTAMP}, ",
        "#{modifyerId,jdbcType=DECIMAL}, #{modifyTs,jdbcType=TIMESTAMP}, ",
        "#{modifyAppsvr,jdbcType=NCHAR}, #{modifyModule,jdbcType=NCHAR}, ",
        "#{dataVersion,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT SEQ_T_QUOTE_PROD.NEXTVAL FROM DUAL", keyProperty="id", before=true, resultType=Long.class)
    int insert(TQuoteProd record);

    @Select({
        "select",
        "ID, QUOTE_ID, LINE_NO, LINE_TYPE, PROD_ID, CHANGE_FLAG, VERSION_NUM, REPEAT_NUM, ",
        "QUOTE_STATUS, DIST_STATUS, SETTLE_STATUS, CREDIT_STATUS, HOME_CURR_CODE, FORE_CURR_CODE, ",
        "CURR_RATE, CALC_PRICE, CURR_CALC_PRICE, QUOTE_PRICE, CURR_QUOTE_PRICE, CALC_AMT, ",
        "CURR_CALC_AMT, QUOTE_AMT, CURR_QUOTE_AMT, CUST_AMT, CURR_CUST_AMT, FORFREE_QTY, ",
        "FORCHECK_QTY, FORKEEP_QTY, FORCUSTSAMPLE_QTY, MANU_QTY, FREE_FLAG, PROD_UOM, ",
        "DISTING_QTY, DIST_QTY, QTY_SPLIT_FLAG, SAMPLE_TYPE, PACKAGE_TYPE, MANU_PACK_TYPE, ",
        "DUE_DATE, DELI_ADDR_ID, DELI_ADDR_DESC, DELI_METHOD, IMPRESSION_CNT, PRINT_COMP_CNT, ",
        "BIND_COMP_CNT, MANU_COMP_DATE, WHIN_QTY, DELI_QTY, LAST_DELI_DATE, SETTLE_FLAG, ",
        "SETTLE_QTY, SETTLE_AMT, CURR_SETTLE_AMT, INV_AMT, RECV_AMT, WH_ID, CANCLE_DATE, ",
        "PAPER_READY_FLAG, REMARK, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION",
        "from T_QUOTE_PROD",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="QUOTE_ID", property="quoteId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LINE_NO", property="lineNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="LINE_TYPE", property="lineType", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_ID", property="prodId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHANGE_FLAG", property="changeFlag", jdbcType=JdbcType.NCHAR),
        @Result(column="VERSION_NUM", property="versionNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="REPEAT_NUM", property="repeatNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_STATUS", property="quoteStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="DIST_STATUS", property="distStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="SETTLE_STATUS", property="settleStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="CREDIT_STATUS", property="creditStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="HOME_CURR_CODE", property="homeCurrCode", jdbcType=JdbcType.NCHAR),
        @Result(column="FORE_CURR_CODE", property="foreCurrCode", jdbcType=JdbcType.NCHAR),
        @Result(column="CURR_RATE", property="currRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="CALC_PRICE", property="calcPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_CALC_PRICE", property="currCalcPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_PRICE", property="quotePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_QUOTE_PRICE", property="currQuotePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CALC_AMT", property="calcAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_CALC_AMT", property="currCalcAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_AMT", property="quoteAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_QUOTE_AMT", property="currQuoteAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_AMT", property="custAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_CUST_AMT", property="currCustAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="FORFREE_QTY", property="forfreeQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="FORCHECK_QTY", property="forcheckQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="FORKEEP_QTY", property="forkeepQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="FORCUSTSAMPLE_QTY", property="forcustsampleQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="MANU_QTY", property="manuQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREE_FLAG", property="freeFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_UOM", property="prodUom", jdbcType=JdbcType.NCHAR),
        @Result(column="DISTING_QTY", property="distingQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIST_QTY", property="distQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="QTY_SPLIT_FLAG", property="qtySplitFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SAMPLE_TYPE", property="sampleType", jdbcType=JdbcType.NCHAR),
        @Result(column="PACKAGE_TYPE", property="packageType", jdbcType=JdbcType.NCHAR),
        @Result(column="MANU_PACK_TYPE", property="manuPackType", jdbcType=JdbcType.NCHAR),
        @Result(column="DUE_DATE", property="dueDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DELI_ADDR_ID", property="deliAddrId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_ADDR_DESC", property="deliAddrDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_METHOD", property="deliMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRESSION_CNT", property="impressionCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRINT_COMP_CNT", property="printCompCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_COMP_CNT", property="bindCompCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="MANU_COMP_DATE", property="manuCompDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="WHIN_QTY", property="whinQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_QTY", property="deliQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="LAST_DELI_DATE", property="lastDeliDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SETTLE_FLAG", property="settleFlag", jdbcType=JdbcType.NCHAR),
        @Result(column="SETTLE_QTY", property="settleQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="SETTLE_AMT", property="settleAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_SETTLE_AMT", property="currSettleAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="INV_AMT", property="invAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="RECV_AMT", property="recvAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="WH_ID", property="whId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CANCLE_DATE", property="cancleDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAPER_READY_FLAG", property="paperReadyFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    TQuoteProd selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, QUOTE_ID, LINE_NO, LINE_TYPE, PROD_ID, CHANGE_FLAG, VERSION_NUM, REPEAT_NUM, ",
        "QUOTE_STATUS, DIST_STATUS, SETTLE_STATUS, CREDIT_STATUS, HOME_CURR_CODE, FORE_CURR_CODE, ",
        "CURR_RATE, CALC_PRICE, CURR_CALC_PRICE, QUOTE_PRICE, CURR_QUOTE_PRICE, CALC_AMT, ",
        "CURR_CALC_AMT, QUOTE_AMT, CURR_QUOTE_AMT, CUST_AMT, CURR_CUST_AMT, FORFREE_QTY, ",
        "FORCHECK_QTY, FORKEEP_QTY, FORCUSTSAMPLE_QTY, MANU_QTY, FREE_FLAG, PROD_UOM, ",
        "DISTING_QTY, DIST_QTY, QTY_SPLIT_FLAG, SAMPLE_TYPE, PACKAGE_TYPE, MANU_PACK_TYPE, ",
        "DUE_DATE, DELI_ADDR_ID, DELI_ADDR_DESC, DELI_METHOD, IMPRESSION_CNT, PRINT_COMP_CNT, ",
        "BIND_COMP_CNT, MANU_COMP_DATE, WHIN_QTY, DELI_QTY, LAST_DELI_DATE, SETTLE_FLAG, ",
        "SETTLE_QTY, SETTLE_AMT, CURR_SETTLE_AMT, INV_AMT, RECV_AMT, WH_ID, CANCLE_DATE, ",
        "PAPER_READY_FLAG, REMARK, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION",
        "from T_QUOTE_PROD"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="QUOTE_ID", property="quoteId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LINE_NO", property="lineNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="LINE_TYPE", property="lineType", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_ID", property="prodId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHANGE_FLAG", property="changeFlag", jdbcType=JdbcType.NCHAR),
        @Result(column="VERSION_NUM", property="versionNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="REPEAT_NUM", property="repeatNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_STATUS", property="quoteStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="DIST_STATUS", property="distStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="SETTLE_STATUS", property="settleStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="CREDIT_STATUS", property="creditStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="HOME_CURR_CODE", property="homeCurrCode", jdbcType=JdbcType.NCHAR),
        @Result(column="FORE_CURR_CODE", property="foreCurrCode", jdbcType=JdbcType.NCHAR),
        @Result(column="CURR_RATE", property="currRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="CALC_PRICE", property="calcPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_CALC_PRICE", property="currCalcPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_PRICE", property="quotePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_QUOTE_PRICE", property="currQuotePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CALC_AMT", property="calcAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_CALC_AMT", property="currCalcAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_AMT", property="quoteAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_QUOTE_AMT", property="currQuoteAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_AMT", property="custAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_CUST_AMT", property="currCustAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="FORFREE_QTY", property="forfreeQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="FORCHECK_QTY", property="forcheckQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="FORKEEP_QTY", property="forkeepQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="FORCUSTSAMPLE_QTY", property="forcustsampleQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="MANU_QTY", property="manuQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREE_FLAG", property="freeFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_UOM", property="prodUom", jdbcType=JdbcType.NCHAR),
        @Result(column="DISTING_QTY", property="distingQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIST_QTY", property="distQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="QTY_SPLIT_FLAG", property="qtySplitFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SAMPLE_TYPE", property="sampleType", jdbcType=JdbcType.NCHAR),
        @Result(column="PACKAGE_TYPE", property="packageType", jdbcType=JdbcType.NCHAR),
        @Result(column="MANU_PACK_TYPE", property="manuPackType", jdbcType=JdbcType.NCHAR),
        @Result(column="DUE_DATE", property="dueDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DELI_ADDR_ID", property="deliAddrId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_ADDR_DESC", property="deliAddrDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_METHOD", property="deliMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="IMPRESSION_CNT", property="impressionCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRINT_COMP_CNT", property="printCompCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_COMP_CNT", property="bindCompCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="MANU_COMP_DATE", property="manuCompDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="WHIN_QTY", property="whinQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_QTY", property="deliQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="LAST_DELI_DATE", property="lastDeliDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SETTLE_FLAG", property="settleFlag", jdbcType=JdbcType.NCHAR),
        @Result(column="SETTLE_QTY", property="settleQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="SETTLE_AMT", property="settleAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_SETTLE_AMT", property="currSettleAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="INV_AMT", property="invAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="RECV_AMT", property="recvAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="WH_ID", property="whId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CANCLE_DATE", property="cancleDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAPER_READY_FLAG", property="paperReadyFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    List<TQuoteProd> selectAll();

    @Update({
        "update T_QUOTE_PROD",
        "set QUOTE_ID = #{quoteId,jdbcType=DECIMAL},",
          "LINE_NO = #{lineNo,jdbcType=DECIMAL},",
          "LINE_TYPE = #{lineType,jdbcType=NCHAR},",
          "PROD_ID = #{prodId,jdbcType=DECIMAL},",
          "CHANGE_FLAG = #{changeFlag,jdbcType=NCHAR},",
          "VERSION_NUM = #{versionNum,jdbcType=DECIMAL},",
          "REPEAT_NUM = #{repeatNum,jdbcType=DECIMAL},",
          "QUOTE_STATUS = #{quoteStatus,jdbcType=NCHAR},",
          "DIST_STATUS = #{distStatus,jdbcType=NCHAR},",
          "SETTLE_STATUS = #{settleStatus,jdbcType=NCHAR},",
          "CREDIT_STATUS = #{creditStatus,jdbcType=NCHAR},",
          "HOME_CURR_CODE = #{homeCurrCode,jdbcType=NCHAR},",
          "FORE_CURR_CODE = #{foreCurrCode,jdbcType=NCHAR},",
          "CURR_RATE = #{currRate,jdbcType=DECIMAL},",
          "CALC_PRICE = #{calcPrice,jdbcType=DECIMAL},",
          "CURR_CALC_PRICE = #{currCalcPrice,jdbcType=DECIMAL},",
          "QUOTE_PRICE = #{quotePrice,jdbcType=DECIMAL},",
          "CURR_QUOTE_PRICE = #{currQuotePrice,jdbcType=DECIMAL},",
          "CALC_AMT = #{calcAmt,jdbcType=DECIMAL},",
          "CURR_CALC_AMT = #{currCalcAmt,jdbcType=DECIMAL},",
          "QUOTE_AMT = #{quoteAmt,jdbcType=DECIMAL},",
          "CURR_QUOTE_AMT = #{currQuoteAmt,jdbcType=DECIMAL},",
          "CUST_AMT = #{custAmt,jdbcType=DECIMAL},",
          "CURR_CUST_AMT = #{currCustAmt,jdbcType=DECIMAL},",
          "FORFREE_QTY = #{forfreeQty,jdbcType=DECIMAL},",
          "FORCHECK_QTY = #{forcheckQty,jdbcType=DECIMAL},",
          "FORKEEP_QTY = #{forkeepQty,jdbcType=DECIMAL},",
          "FORCUSTSAMPLE_QTY = #{forcustsampleQty,jdbcType=DECIMAL},",
          "MANU_QTY = #{manuQty,jdbcType=DECIMAL},",
          "FREE_FLAG = #{freeFlag,jdbcType=DECIMAL},",
          "PROD_UOM = #{prodUom,jdbcType=NCHAR},",
          "DISTING_QTY = #{distingQty,jdbcType=DECIMAL},",
          "DIST_QTY = #{distQty,jdbcType=DECIMAL},",
          "QTY_SPLIT_FLAG = #{qtySplitFlag,jdbcType=DECIMAL},",
          "SAMPLE_TYPE = #{sampleType,jdbcType=NCHAR},",
          "PACKAGE_TYPE = #{packageType,jdbcType=NCHAR},",
          "MANU_PACK_TYPE = #{manuPackType,jdbcType=NCHAR},",
          "DUE_DATE = #{dueDate,jdbcType=TIMESTAMP},",
          "DELI_ADDR_ID = #{deliAddrId,jdbcType=DECIMAL},",
          "DELI_ADDR_DESC = #{deliAddrDesc,jdbcType=NCHAR},",
          "DELI_METHOD = #{deliMethod,jdbcType=NCHAR},",
          "IMPRESSION_CNT = #{impressionCnt,jdbcType=DECIMAL},",
          "PRINT_COMP_CNT = #{printCompCnt,jdbcType=DECIMAL},",
          "BIND_COMP_CNT = #{bindCompCnt,jdbcType=DECIMAL},",
          "MANU_COMP_DATE = #{manuCompDate,jdbcType=TIMESTAMP},",
          "WHIN_QTY = #{whinQty,jdbcType=DECIMAL},",
          "DELI_QTY = #{deliQty,jdbcType=DECIMAL},",
          "LAST_DELI_DATE = #{lastDeliDate,jdbcType=TIMESTAMP},",
          "SETTLE_FLAG = #{settleFlag,jdbcType=NCHAR},",
          "SETTLE_QTY = #{settleQty,jdbcType=DECIMAL},",
          "SETTLE_AMT = #{settleAmt,jdbcType=DECIMAL},",
          "CURR_SETTLE_AMT = #{currSettleAmt,jdbcType=DECIMAL},",
          "INV_AMT = #{invAmt,jdbcType=DECIMAL},",
          "RECV_AMT = #{recvAmt,jdbcType=DECIMAL},",
          "WH_ID = #{whId,jdbcType=DECIMAL},",
          "CANCLE_DATE = #{cancleDate,jdbcType=TIMESTAMP},",
          "PAPER_READY_FLAG = #{paperReadyFlag,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=NCHAR},",
          "LOCKER_ID = #{lockerId,jdbcType=DECIMAL},",
          "LOCK_TS = #{lockTs,jdbcType=TIMESTAMP},",
          "MODIFYER_ID = #{modifyerId,jdbcType=DECIMAL},",
          "MODIFY_TS = #{modifyTs,jdbcType=TIMESTAMP},",
          "MODIFY_APPSVR = #{modifyAppsvr,jdbcType=NCHAR},",
          "MODIFY_MODULE = #{modifyModule,jdbcType=NCHAR},",
          "DATA_VERSION = #{dataVersion,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TQuoteProd record);
}