package com.el.cfg.mapper;

import com.el.cfg.domain.TQuote;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TQuoteMapper {
    @Delete({
        "delete from T_QUOTE",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into T_QUOTE (ID, OU_ID, ",
        "MCU_ID, QUOTE_NO, CUST_ID, ",
        "DUE_DATE, MANU_DUE_DATE, ",
        "AGENT_ID, QUOTE_DATE, ",
        "EFFECT_DATE, PAYMENT_METHOD, ",
        "PAYMENT_TERMS, QUOTE_STATUS, ",
        "QUOTE_TYPE, QUOTE_NAME, ",
        "CUST_SO_NO, MERCHER_ID, ",
        "SALE_MANAGER_ID, CONTRACT_NO, ",
        "BATCH_DESC, APPRER_ID, ",
        "APPR_DATE, APPR_COMMENT, ",
        "PRICE_APPRER_ID, PRICE_APPR_DATE, ",
        "PRICE_APPR_COMMENT, PRICE_CALC_DATE, ",
        "HOME_CURR_CODE, FORE_CURR_CODE, ",
        "CURR_RATE, AMT, CURR_AMT, ",
        "GREEN_FLAG, SECRET_FLAG, ",
        "SPECIAL_REMARK, DELI_ADDR_ID, ",
        "DELI_ADDR_DESC, DELI_CONT_ID, ",
        "DELI_CONT_DESC, DELI_METHOD, ",
        "PRINT_ADDUP_RATIO, BIND_ADDUP_RATIO, ",
        "PROD_DESC, VERSION, REMARK, ",
        "URC_MCU1, URC_MCU2, ",
        "URC_MCU3, URC_STATUS1, ",
        "URC_STATUS2, URC_STATUS3, ",
        "URC_C1, URC_C2, URC_C3, ",
        "URC_C4, URC_C5, URC_D1, ",
        "URC_D2, URC_D3, ",
        "URC_N1, URC_N2, URC_N3, ",
        "URC_N4, URC_N5, LOCKER_ID, ",
        "LOCK_TS, MODIFYER_ID, ",
        "MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION)",
        "values (#{id,jdbcType=DECIMAL}, #{ouId,jdbcType=DECIMAL}, ",
        "#{mcuId,jdbcType=DECIMAL}, #{quoteNo,jdbcType=NCHAR}, #{custId,jdbcType=DECIMAL}, ",
        "#{dueDate,jdbcType=TIMESTAMP}, #{manuDueDate,jdbcType=TIMESTAMP}, ",
        "#{agentId,jdbcType=DECIMAL}, #{quoteDate,jdbcType=TIMESTAMP}, ",
        "#{effectDate,jdbcType=TIMESTAMP}, #{paymentMethod,jdbcType=NCHAR}, ",
        "#{paymentTerms,jdbcType=NCHAR}, #{quoteStatus,jdbcType=NCHAR}, ",
        "#{quoteType,jdbcType=NCHAR}, #{quoteName,jdbcType=NCHAR}, ",
        "#{custSoNo,jdbcType=NCHAR}, #{mercherId,jdbcType=DECIMAL}, ",
        "#{saleManagerId,jdbcType=DECIMAL}, #{contractNo,jdbcType=NCHAR}, ",
        "#{batchDesc,jdbcType=NCHAR}, #{apprerId,jdbcType=DECIMAL}, ",
        "#{apprDate,jdbcType=TIMESTAMP}, #{apprComment,jdbcType=NCHAR}, ",
        "#{priceApprerId,jdbcType=DECIMAL}, #{priceApprDate,jdbcType=TIMESTAMP}, ",
        "#{priceApprComment,jdbcType=NCHAR}, #{priceCalcDate,jdbcType=TIMESTAMP}, ",
        "#{homeCurrCode,jdbcType=NCHAR}, #{foreCurrCode,jdbcType=NCHAR}, ",
        "#{currRate,jdbcType=DECIMAL}, #{amt,jdbcType=DECIMAL}, #{currAmt,jdbcType=DECIMAL}, ",
        "#{greenFlag,jdbcType=DECIMAL}, #{secretFlag,jdbcType=DECIMAL}, ",
        "#{specialRemark,jdbcType=NCHAR}, #{deliAddrId,jdbcType=DECIMAL}, ",
        "#{deliAddrDesc,jdbcType=NCHAR}, #{deliContId,jdbcType=DECIMAL}, ",
        "#{deliContDesc,jdbcType=NCHAR}, #{deliMethod,jdbcType=NCHAR}, ",
        "#{printAddupRatio,jdbcType=DECIMAL}, #{bindAddupRatio,jdbcType=DECIMAL}, ",
        "#{prodDesc,jdbcType=NCHAR}, #{version,jdbcType=NCHAR}, #{remark,jdbcType=NCHAR}, ",
        "#{urcMcu1,jdbcType=DECIMAL}, #{urcMcu2,jdbcType=DECIMAL}, ",
        "#{urcMcu3,jdbcType=DECIMAL}, #{urcStatus1,jdbcType=NCHAR}, ",
        "#{urcStatus2,jdbcType=NCHAR}, #{urcStatus3,jdbcType=NCHAR}, ",
        "#{urcC1,jdbcType=NCHAR}, #{urcC2,jdbcType=NCHAR}, #{urcC3,jdbcType=NCHAR}, ",
        "#{urcC4,jdbcType=NCHAR}, #{urcC5,jdbcType=NCHAR}, #{urcD1,jdbcType=TIMESTAMP}, ",
        "#{urcD2,jdbcType=TIMESTAMP}, #{urcD3,jdbcType=TIMESTAMP}, ",
        "#{urcN1,jdbcType=DECIMAL}, #{urcN2,jdbcType=DECIMAL}, #{urcN3,jdbcType=DECIMAL}, ",
        "#{urcN4,jdbcType=DECIMAL}, #{urcN5,jdbcType=DECIMAL}, #{lockerId,jdbcType=DECIMAL}, ",
        "#{lockTs,jdbcType=TIMESTAMP}, #{modifyerId,jdbcType=DECIMAL}, ",
        "#{modifyTs,jdbcType=TIMESTAMP}, #{modifyAppsvr,jdbcType=NCHAR}, ",
        "#{modifyModule,jdbcType=NCHAR}, #{dataVersion,jdbcType=DECIMAL})"
    })
    @SelectKey(statement="SELECT SEQ_T_QUOTE.NEXTVAL FROM DUAL", keyProperty="id", before=true, resultType=Long.class)
    int insert(TQuote record);

    @Select({
        "select",
        "ID, OU_ID, MCU_ID, QUOTE_NO, CUST_ID, DUE_DATE, MANU_DUE_DATE, AGENT_ID, QUOTE_DATE, ",
        "EFFECT_DATE, PAYMENT_METHOD, PAYMENT_TERMS, QUOTE_STATUS, QUOTE_TYPE, QUOTE_NAME, ",
        "CUST_SO_NO, MERCHER_ID, SALE_MANAGER_ID, CONTRACT_NO, BATCH_DESC, APPRER_ID, ",
        "APPR_DATE, APPR_COMMENT, PRICE_APPRER_ID, PRICE_APPR_DATE, PRICE_APPR_COMMENT, ",
        "PRICE_CALC_DATE, HOME_CURR_CODE, FORE_CURR_CODE, CURR_RATE, AMT, CURR_AMT, GREEN_FLAG, ",
        "SECRET_FLAG, SPECIAL_REMARK, DELI_ADDR_ID, DELI_ADDR_DESC, DELI_CONT_ID, DELI_CONT_DESC, ",
        "DELI_METHOD, PRINT_ADDUP_RATIO, BIND_ADDUP_RATIO, PROD_DESC, VERSION, REMARK, ",
        "URC_MCU1, URC_MCU2, URC_MCU3, URC_STATUS1, URC_STATUS2, URC_STATUS3, URC_C1, ",
        "URC_C2, URC_C3, URC_C4, URC_C5, URC_D1, URC_D2, URC_D3, URC_N1, URC_N2, URC_N3, ",
        "URC_N4, URC_N5, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, MODIFY_MODULE, ",
        "DATA_VERSION",
        "from T_QUOTE",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCU_ID", property="mcuId", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_NO", property="quoteNo", jdbcType=JdbcType.NCHAR),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DUE_DATE", property="dueDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MANU_DUE_DATE", property="manuDueDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="AGENT_ID", property="agentId", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_DATE", property="quoteDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EFFECT_DATE", property="effectDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAYMENT_METHOD", property="paymentMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="PAYMENT_TERMS", property="paymentTerms", jdbcType=JdbcType.NCHAR),
        @Result(column="QUOTE_STATUS", property="quoteStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="QUOTE_TYPE", property="quoteType", jdbcType=JdbcType.NCHAR),
        @Result(column="QUOTE_NAME", property="quoteName", jdbcType=JdbcType.NCHAR),
        @Result(column="CUST_SO_NO", property="custSoNo", jdbcType=JdbcType.NCHAR),
        @Result(column="MERCHER_ID", property="mercherId", jdbcType=JdbcType.DECIMAL),
        @Result(column="SALE_MANAGER_ID", property="saleManagerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CONTRACT_NO", property="contractNo", jdbcType=JdbcType.NCHAR),
        @Result(column="BATCH_DESC", property="batchDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="APPRER_ID", property="apprerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="APPR_DATE", property="apprDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="APPR_COMMENT", property="apprComment", jdbcType=JdbcType.NCHAR),
        @Result(column="PRICE_APPRER_ID", property="priceApprerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRICE_APPR_DATE", property="priceApprDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PRICE_APPR_COMMENT", property="priceApprComment", jdbcType=JdbcType.NCHAR),
        @Result(column="PRICE_CALC_DATE", property="priceCalcDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HOME_CURR_CODE", property="homeCurrCode", jdbcType=JdbcType.NCHAR),
        @Result(column="FORE_CURR_CODE", property="foreCurrCode", jdbcType=JdbcType.NCHAR),
        @Result(column="CURR_RATE", property="currRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_AMT", property="currAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="GREEN_FLAG", property="greenFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SECRET_FLAG", property="secretFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPECIAL_REMARK", property="specialRemark", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_ADDR_ID", property="deliAddrId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_ADDR_DESC", property="deliAddrDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_CONT_ID", property="deliContId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_CONT_DESC", property="deliContDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_METHOD", property="deliMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINT_ADDUP_RATIO", property="printAddupRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_ADDUP_RATIO", property="bindAddupRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_DESC", property="prodDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.NCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_MCU1", property="urcMcu1", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_MCU2", property="urcMcu2", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_MCU3", property="urcMcu3", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_STATUS1", property="urcStatus1", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_STATUS2", property="urcStatus2", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_STATUS3", property="urcStatus3", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C1", property="urcC1", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C2", property="urcC2", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C3", property="urcC3", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C4", property="urcC4", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C5", property="urcC5", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_D1", property="urcD1", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="URC_D2", property="urcD2", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="URC_D3", property="urcD3", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="URC_N1", property="urcN1", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_N2", property="urcN2", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_N3", property="urcN3", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_N4", property="urcN4", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_N5", property="urcN5", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    TQuote selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, OU_ID, MCU_ID, QUOTE_NO, CUST_ID, DUE_DATE, MANU_DUE_DATE, AGENT_ID, QUOTE_DATE, ",
        "EFFECT_DATE, PAYMENT_METHOD, PAYMENT_TERMS, QUOTE_STATUS, QUOTE_TYPE, QUOTE_NAME, ",
        "CUST_SO_NO, MERCHER_ID, SALE_MANAGER_ID, CONTRACT_NO, BATCH_DESC, APPRER_ID, ",
        "APPR_DATE, APPR_COMMENT, PRICE_APPRER_ID, PRICE_APPR_DATE, PRICE_APPR_COMMENT, ",
        "PRICE_CALC_DATE, HOME_CURR_CODE, FORE_CURR_CODE, CURR_RATE, AMT, CURR_AMT, GREEN_FLAG, ",
        "SECRET_FLAG, SPECIAL_REMARK, DELI_ADDR_ID, DELI_ADDR_DESC, DELI_CONT_ID, DELI_CONT_DESC, ",
        "DELI_METHOD, PRINT_ADDUP_RATIO, BIND_ADDUP_RATIO, PROD_DESC, VERSION, REMARK, ",
        "URC_MCU1, URC_MCU2, URC_MCU3, URC_STATUS1, URC_STATUS2, URC_STATUS3, URC_C1, ",
        "URC_C2, URC_C3, URC_C4, URC_C5, URC_D1, URC_D2, URC_D3, URC_N1, URC_N2, URC_N3, ",
        "URC_N4, URC_N5, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, MODIFY_MODULE, ",
        "DATA_VERSION",
        "from T_QUOTE"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MCU_ID", property="mcuId", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_NO", property="quoteNo", jdbcType=JdbcType.NCHAR),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DUE_DATE", property="dueDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MANU_DUE_DATE", property="manuDueDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="AGENT_ID", property="agentId", jdbcType=JdbcType.DECIMAL),
        @Result(column="QUOTE_DATE", property="quoteDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="EFFECT_DATE", property="effectDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAYMENT_METHOD", property="paymentMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="PAYMENT_TERMS", property="paymentTerms", jdbcType=JdbcType.NCHAR),
        @Result(column="QUOTE_STATUS", property="quoteStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="QUOTE_TYPE", property="quoteType", jdbcType=JdbcType.NCHAR),
        @Result(column="QUOTE_NAME", property="quoteName", jdbcType=JdbcType.NCHAR),
        @Result(column="CUST_SO_NO", property="custSoNo", jdbcType=JdbcType.NCHAR),
        @Result(column="MERCHER_ID", property="mercherId", jdbcType=JdbcType.DECIMAL),
        @Result(column="SALE_MANAGER_ID", property="saleManagerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CONTRACT_NO", property="contractNo", jdbcType=JdbcType.NCHAR),
        @Result(column="BATCH_DESC", property="batchDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="APPRER_ID", property="apprerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="APPR_DATE", property="apprDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="APPR_COMMENT", property="apprComment", jdbcType=JdbcType.NCHAR),
        @Result(column="PRICE_APPRER_ID", property="priceApprerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRICE_APPR_DATE", property="priceApprDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PRICE_APPR_COMMENT", property="priceApprComment", jdbcType=JdbcType.NCHAR),
        @Result(column="PRICE_CALC_DATE", property="priceCalcDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="HOME_CURR_CODE", property="homeCurrCode", jdbcType=JdbcType.NCHAR),
        @Result(column="FORE_CURR_CODE", property="foreCurrCode", jdbcType=JdbcType.NCHAR),
        @Result(column="CURR_RATE", property="currRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_AMT", property="currAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="GREEN_FLAG", property="greenFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SECRET_FLAG", property="secretFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPECIAL_REMARK", property="specialRemark", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_ADDR_ID", property="deliAddrId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_ADDR_DESC", property="deliAddrDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_CONT_ID", property="deliContId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_CONT_DESC", property="deliContDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_METHOD", property="deliMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="PRINT_ADDUP_RATIO", property="printAddupRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_ADDUP_RATIO", property="bindAddupRatio", jdbcType=JdbcType.DECIMAL),
        @Result(column="PROD_DESC", property="prodDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="VERSION", property="version", jdbcType=JdbcType.NCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_MCU1", property="urcMcu1", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_MCU2", property="urcMcu2", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_MCU3", property="urcMcu3", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_STATUS1", property="urcStatus1", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_STATUS2", property="urcStatus2", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_STATUS3", property="urcStatus3", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C1", property="urcC1", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C2", property="urcC2", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C3", property="urcC3", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C4", property="urcC4", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_C5", property="urcC5", jdbcType=JdbcType.NCHAR),
        @Result(column="URC_D1", property="urcD1", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="URC_D2", property="urcD2", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="URC_D3", property="urcD3", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="URC_N1", property="urcN1", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_N2", property="urcN2", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_N3", property="urcN3", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_N4", property="urcN4", jdbcType=JdbcType.DECIMAL),
        @Result(column="URC_N5", property="urcN5", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL)
    })
    List<TQuote> selectAll();

    @Update({
        "update T_QUOTE",
        "set OU_ID = #{ouId,jdbcType=DECIMAL},",
          "MCU_ID = #{mcuId,jdbcType=DECIMAL},",
          "QUOTE_NO = #{quoteNo,jdbcType=NCHAR},",
          "CUST_ID = #{custId,jdbcType=DECIMAL},",
          "DUE_DATE = #{dueDate,jdbcType=TIMESTAMP},",
          "MANU_DUE_DATE = #{manuDueDate,jdbcType=TIMESTAMP},",
          "AGENT_ID = #{agentId,jdbcType=DECIMAL},",
          "QUOTE_DATE = #{quoteDate,jdbcType=TIMESTAMP},",
          "EFFECT_DATE = #{effectDate,jdbcType=TIMESTAMP},",
          "PAYMENT_METHOD = #{paymentMethod,jdbcType=NCHAR},",
          "PAYMENT_TERMS = #{paymentTerms,jdbcType=NCHAR},",
          "QUOTE_STATUS = #{quoteStatus,jdbcType=NCHAR},",
          "QUOTE_TYPE = #{quoteType,jdbcType=NCHAR},",
          "QUOTE_NAME = #{quoteName,jdbcType=NCHAR},",
          "CUST_SO_NO = #{custSoNo,jdbcType=NCHAR},",
          "MERCHER_ID = #{mercherId,jdbcType=DECIMAL},",
          "SALE_MANAGER_ID = #{saleManagerId,jdbcType=DECIMAL},",
          "CONTRACT_NO = #{contractNo,jdbcType=NCHAR},",
          "BATCH_DESC = #{batchDesc,jdbcType=NCHAR},",
          "APPRER_ID = #{apprerId,jdbcType=DECIMAL},",
          "APPR_DATE = #{apprDate,jdbcType=TIMESTAMP},",
          "APPR_COMMENT = #{apprComment,jdbcType=NCHAR},",
          "PRICE_APPRER_ID = #{priceApprerId,jdbcType=DECIMAL},",
          "PRICE_APPR_DATE = #{priceApprDate,jdbcType=TIMESTAMP},",
          "PRICE_APPR_COMMENT = #{priceApprComment,jdbcType=NCHAR},",
          "PRICE_CALC_DATE = #{priceCalcDate,jdbcType=TIMESTAMP},",
          "HOME_CURR_CODE = #{homeCurrCode,jdbcType=NCHAR},",
          "FORE_CURR_CODE = #{foreCurrCode,jdbcType=NCHAR},",
          "CURR_RATE = #{currRate,jdbcType=DECIMAL},",
          "AMT = #{amt,jdbcType=DECIMAL},",
          "CURR_AMT = #{currAmt,jdbcType=DECIMAL},",
          "GREEN_FLAG = #{greenFlag,jdbcType=DECIMAL},",
          "SECRET_FLAG = #{secretFlag,jdbcType=DECIMAL},",
          "SPECIAL_REMARK = #{specialRemark,jdbcType=NCHAR},",
          "DELI_ADDR_ID = #{deliAddrId,jdbcType=DECIMAL},",
          "DELI_ADDR_DESC = #{deliAddrDesc,jdbcType=NCHAR},",
          "DELI_CONT_ID = #{deliContId,jdbcType=DECIMAL},",
          "DELI_CONT_DESC = #{deliContDesc,jdbcType=NCHAR},",
          "DELI_METHOD = #{deliMethod,jdbcType=NCHAR},",
          "PRINT_ADDUP_RATIO = #{printAddupRatio,jdbcType=DECIMAL},",
          "BIND_ADDUP_RATIO = #{bindAddupRatio,jdbcType=DECIMAL},",
          "PROD_DESC = #{prodDesc,jdbcType=NCHAR},",
          "VERSION = #{version,jdbcType=NCHAR},",
          "REMARK = #{remark,jdbcType=NCHAR},",
          "URC_MCU1 = #{urcMcu1,jdbcType=DECIMAL},",
          "URC_MCU2 = #{urcMcu2,jdbcType=DECIMAL},",
          "URC_MCU3 = #{urcMcu3,jdbcType=DECIMAL},",
          "URC_STATUS1 = #{urcStatus1,jdbcType=NCHAR},",
          "URC_STATUS2 = #{urcStatus2,jdbcType=NCHAR},",
          "URC_STATUS3 = #{urcStatus3,jdbcType=NCHAR},",
          "URC_C1 = #{urcC1,jdbcType=NCHAR},",
          "URC_C2 = #{urcC2,jdbcType=NCHAR},",
          "URC_C3 = #{urcC3,jdbcType=NCHAR},",
          "URC_C4 = #{urcC4,jdbcType=NCHAR},",
          "URC_C5 = #{urcC5,jdbcType=NCHAR},",
          "URC_D1 = #{urcD1,jdbcType=TIMESTAMP},",
          "URC_D2 = #{urcD2,jdbcType=TIMESTAMP},",
          "URC_D3 = #{urcD3,jdbcType=TIMESTAMP},",
          "URC_N1 = #{urcN1,jdbcType=DECIMAL},",
          "URC_N2 = #{urcN2,jdbcType=DECIMAL},",
          "URC_N3 = #{urcN3,jdbcType=DECIMAL},",
          "URC_N4 = #{urcN4,jdbcType=DECIMAL},",
          "URC_N5 = #{urcN5,jdbcType=DECIMAL},",
          "LOCKER_ID = #{lockerId,jdbcType=DECIMAL},",
          "LOCK_TS = #{lockTs,jdbcType=TIMESTAMP},",
          "MODIFYER_ID = #{modifyerId,jdbcType=DECIMAL},",
          "MODIFY_TS = #{modifyTs,jdbcType=TIMESTAMP},",
          "MODIFY_APPSVR = #{modifyAppsvr,jdbcType=NCHAR},",
          "MODIFY_MODULE = #{modifyModule,jdbcType=NCHAR},",
          "DATA_VERSION = #{dataVersion,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TQuote record);
}