package com.el.cfg.mapper;

import com.el.cfg.domain.TSoManu;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TSoManuMapper {
    @Delete({
        "delete from T_SO_MANU",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into T_SO_MANU (ID, SO_ID, ",
        "SO_PROD_ID, DIST_METHOD, ",
        "ACPT_TIME, ACPT_STATUS, ",
        "DIST_QTY, CALC_PRICE, ",
        "CALC_AMT, ACPT_AMT, ",
        "ACPT_COMMENT, ACPT_USER, ",
        "RETURN_DATE, RETURN_COMMENT, ",
        "RETURN_USER, PLAN_DELI_DATE, ",
        "PAPER_READY_STATUS, PAPER_APPRER, ",
        "PAPER_APPR_DATE, MANU_STATUS, ",
        "WHIN_STATUS, DELI_STATUS, ",
        "FACT_SETTLE_STATUS, PROD_INFO_STATUS, ",
        "PROD_APPRER, PROD_APPR_DATE, ",
        "IMPRESSION_CNT, PRINT_COMP_CNT, ",
        "BIND_COMP_CNT, WHIN_QTY, ",
        "DELI_QTY, MANU_COMP_DATE, ",
        "AMT, REMARK, LOCKER_ID, ",
        "LOCK_TS, MODIFYER_ID, ",
        "MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION, ",
        "FACT_ID, CLOSE_DESC, ",
        "MANU_DIST_ID, 字段45)",
        "values (#{id,jdbcType=DECIMAL}, #{soId,jdbcType=DECIMAL}, ",
        "#{soProdId,jdbcType=DECIMAL}, #{distMethod,jdbcType=NCHAR}, ",
        "#{acptTime,jdbcType=TIMESTAMP}, #{acptStatus,jdbcType=NCHAR}, ",
        "#{distQty,jdbcType=DECIMAL}, #{calcPrice,jdbcType=DECIMAL}, ",
        "#{calcAmt,jdbcType=DECIMAL}, #{acptAmt,jdbcType=DECIMAL}, ",
        "#{acptComment,jdbcType=NCHAR}, #{acptUser,jdbcType=NCHAR}, ",
        "#{returnDate,jdbcType=TIMESTAMP}, #{returnComment,jdbcType=NCHAR}, ",
        "#{returnUser,jdbcType=NCHAR}, #{planDeliDate,jdbcType=TIMESTAMP}, ",
        "#{paperReadyStatus,jdbcType=NCHAR}, #{paperApprer,jdbcType=NCHAR}, ",
        "#{paperApprDate,jdbcType=TIMESTAMP}, #{manuStatus,jdbcType=NCHAR}, ",
        "#{whinStatus,jdbcType=NCHAR}, #{deliStatus,jdbcType=NCHAR}, ",
        "#{factSettleStatus,jdbcType=NCHAR}, #{prodInfoStatus,jdbcType=NCHAR}, ",
        "#{prodApprer,jdbcType=NCHAR}, #{prodApprDate,jdbcType=TIMESTAMP}, ",
        "#{impressionCnt,jdbcType=DECIMAL}, #{printCompCnt,jdbcType=DECIMAL}, ",
        "#{bindCompCnt,jdbcType=DECIMAL}, #{whinQty,jdbcType=DECIMAL}, ",
        "#{deliQty,jdbcType=DECIMAL}, #{manuCompDate,jdbcType=TIMESTAMP}, ",
        "#{amt,jdbcType=DECIMAL}, #{remark,jdbcType=NCHAR}, #{lockerId,jdbcType=DECIMAL}, ",
        "#{lockTs,jdbcType=TIMESTAMP}, #{modifyerId,jdbcType=DECIMAL}, ",
        "#{modifyTs,jdbcType=TIMESTAMP}, #{modifyAppsvr,jdbcType=NCHAR}, ",
        "#{modifyModule,jdbcType=NCHAR}, #{dataVersion,jdbcType=DECIMAL}, ",
        "#{factId,jdbcType=DECIMAL}, #{closeDesc,jdbcType=NCHAR}, ",
        "#{manuDistId,jdbcType=DECIMAL}, #{字段45,jdbcType=NCHAR})"
    })
    @SelectKey(statement="SELECT SEQ_T_SO_MANU.NEXTVAL FROM DUAL", keyProperty="id", before=true, resultType=Long.class)
    int insert(TSoManu record);

    @Select({
        "select",
        "ID, SO_ID, SO_PROD_ID, DIST_METHOD, ACPT_TIME, ACPT_STATUS, DIST_QTY, CALC_PRICE, ",
        "CALC_AMT, ACPT_AMT, ACPT_COMMENT, ACPT_USER, RETURN_DATE, RETURN_COMMENT, RETURN_USER, ",
        "PLAN_DELI_DATE, PAPER_READY_STATUS, PAPER_APPRER, PAPER_APPR_DATE, MANU_STATUS, ",
        "WHIN_STATUS, DELI_STATUS, FACT_SETTLE_STATUS, PROD_INFO_STATUS, PROD_APPRER, ",
        "PROD_APPR_DATE, IMPRESSION_CNT, PRINT_COMP_CNT, BIND_COMP_CNT, WHIN_QTY, DELI_QTY, ",
        "MANU_COMP_DATE, AMT, REMARK, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION, FACT_ID, CLOSE_DESC, MANU_DIST_ID, 字段45",
        "from T_SO_MANU",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SO_ID", property="soId", jdbcType=JdbcType.DECIMAL),
        @Result(column="SO_PROD_ID", property="soProdId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIST_METHOD", property="distMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="ACPT_TIME", property="acptTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ACPT_STATUS", property="acptStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="DIST_QTY", property="distQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="CALC_PRICE", property="calcPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CALC_AMT", property="calcAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACPT_AMT", property="acptAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACPT_COMMENT", property="acptComment", jdbcType=JdbcType.NCHAR),
        @Result(column="ACPT_USER", property="acptUser", jdbcType=JdbcType.NCHAR),
        @Result(column="RETURN_DATE", property="returnDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RETURN_COMMENT", property="returnComment", jdbcType=JdbcType.NCHAR),
        @Result(column="RETURN_USER", property="returnUser", jdbcType=JdbcType.NCHAR),
        @Result(column="PLAN_DELI_DATE", property="planDeliDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAPER_READY_STATUS", property="paperReadyStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_APPRER", property="paperApprer", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_APPR_DATE", property="paperApprDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MANU_STATUS", property="manuStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="WHIN_STATUS", property="whinStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_STATUS", property="deliStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="FACT_SETTLE_STATUS", property="factSettleStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_INFO_STATUS", property="prodInfoStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_APPRER", property="prodApprer", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_APPR_DATE", property="prodApprDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="IMPRESSION_CNT", property="impressionCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRINT_COMP_CNT", property="printCompCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_COMP_CNT", property="bindCompCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="WHIN_QTY", property="whinQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_QTY", property="deliQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="MANU_COMP_DATE", property="manuCompDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL),
        @Result(column="FACT_ID", property="factId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CLOSE_DESC", property="closeDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="MANU_DIST_ID", property="manuDistId", jdbcType=JdbcType.DECIMAL),
        @Result(column="字段45", property="字段45", jdbcType=JdbcType.NCHAR)
    })
    TSoManu selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, SO_ID, SO_PROD_ID, DIST_METHOD, ACPT_TIME, ACPT_STATUS, DIST_QTY, CALC_PRICE, ",
        "CALC_AMT, ACPT_AMT, ACPT_COMMENT, ACPT_USER, RETURN_DATE, RETURN_COMMENT, RETURN_USER, ",
        "PLAN_DELI_DATE, PAPER_READY_STATUS, PAPER_APPRER, PAPER_APPR_DATE, MANU_STATUS, ",
        "WHIN_STATUS, DELI_STATUS, FACT_SETTLE_STATUS, PROD_INFO_STATUS, PROD_APPRER, ",
        "PROD_APPR_DATE, IMPRESSION_CNT, PRINT_COMP_CNT, BIND_COMP_CNT, WHIN_QTY, DELI_QTY, ",
        "MANU_COMP_DATE, AMT, REMARK, LOCKER_ID, LOCK_TS, MODIFYER_ID, MODIFY_TS, MODIFY_APPSVR, ",
        "MODIFY_MODULE, DATA_VERSION, FACT_ID, CLOSE_DESC, MANU_DIST_ID, 字段45",
        "from T_SO_MANU"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="SO_ID", property="soId", jdbcType=JdbcType.DECIMAL),
        @Result(column="SO_PROD_ID", property="soProdId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIST_METHOD", property="distMethod", jdbcType=JdbcType.NCHAR),
        @Result(column="ACPT_TIME", property="acptTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="ACPT_STATUS", property="acptStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="DIST_QTY", property="distQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="CALC_PRICE", property="calcPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CALC_AMT", property="calcAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACPT_AMT", property="acptAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACPT_COMMENT", property="acptComment", jdbcType=JdbcType.NCHAR),
        @Result(column="ACPT_USER", property="acptUser", jdbcType=JdbcType.NCHAR),
        @Result(column="RETURN_DATE", property="returnDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RETURN_COMMENT", property="returnComment", jdbcType=JdbcType.NCHAR),
        @Result(column="RETURN_USER", property="returnUser", jdbcType=JdbcType.NCHAR),
        @Result(column="PLAN_DELI_DATE", property="planDeliDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAPER_READY_STATUS", property="paperReadyStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_APPRER", property="paperApprer", jdbcType=JdbcType.NCHAR),
        @Result(column="PAPER_APPR_DATE", property="paperApprDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MANU_STATUS", property="manuStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="WHIN_STATUS", property="whinStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="DELI_STATUS", property="deliStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="FACT_SETTLE_STATUS", property="factSettleStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_INFO_STATUS", property="prodInfoStatus", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_APPRER", property="prodApprer", jdbcType=JdbcType.NCHAR),
        @Result(column="PROD_APPR_DATE", property="prodApprDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="IMPRESSION_CNT", property="impressionCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="PRINT_COMP_CNT", property="printCompCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="BIND_COMP_CNT", property="bindCompCnt", jdbcType=JdbcType.DECIMAL),
        @Result(column="WHIN_QTY", property="whinQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELI_QTY", property="deliQty", jdbcType=JdbcType.DECIMAL),
        @Result(column="MANU_COMP_DATE", property="manuCompDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NCHAR),
        @Result(column="LOCKER_ID", property="lockerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="LOCK_TS", property="lockTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFYER_ID", property="modifyerId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TS", property="modifyTs", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_APPSVR", property="modifyAppsvr", jdbcType=JdbcType.NCHAR),
        @Result(column="MODIFY_MODULE", property="modifyModule", jdbcType=JdbcType.NCHAR),
        @Result(column="DATA_VERSION", property="dataVersion", jdbcType=JdbcType.DECIMAL),
        @Result(column="FACT_ID", property="factId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CLOSE_DESC", property="closeDesc", jdbcType=JdbcType.NCHAR),
        @Result(column="MANU_DIST_ID", property="manuDistId", jdbcType=JdbcType.DECIMAL),
        @Result(column="字段45", property="字段45", jdbcType=JdbcType.NCHAR)
    })
    List<TSoManu> selectAll();

    @Update({
        "update T_SO_MANU",
        "set SO_ID = #{soId,jdbcType=DECIMAL},",
          "SO_PROD_ID = #{soProdId,jdbcType=DECIMAL},",
          "DIST_METHOD = #{distMethod,jdbcType=NCHAR},",
          "ACPT_TIME = #{acptTime,jdbcType=TIMESTAMP},",
          "ACPT_STATUS = #{acptStatus,jdbcType=NCHAR},",
          "DIST_QTY = #{distQty,jdbcType=DECIMAL},",
          "CALC_PRICE = #{calcPrice,jdbcType=DECIMAL},",
          "CALC_AMT = #{calcAmt,jdbcType=DECIMAL},",
          "ACPT_AMT = #{acptAmt,jdbcType=DECIMAL},",
          "ACPT_COMMENT = #{acptComment,jdbcType=NCHAR},",
          "ACPT_USER = #{acptUser,jdbcType=NCHAR},",
          "RETURN_DATE = #{returnDate,jdbcType=TIMESTAMP},",
          "RETURN_COMMENT = #{returnComment,jdbcType=NCHAR},",
          "RETURN_USER = #{returnUser,jdbcType=NCHAR},",
          "PLAN_DELI_DATE = #{planDeliDate,jdbcType=TIMESTAMP},",
          "PAPER_READY_STATUS = #{paperReadyStatus,jdbcType=NCHAR},",
          "PAPER_APPRER = #{paperApprer,jdbcType=NCHAR},",
          "PAPER_APPR_DATE = #{paperApprDate,jdbcType=TIMESTAMP},",
          "MANU_STATUS = #{manuStatus,jdbcType=NCHAR},",
          "WHIN_STATUS = #{whinStatus,jdbcType=NCHAR},",
          "DELI_STATUS = #{deliStatus,jdbcType=NCHAR},",
          "FACT_SETTLE_STATUS = #{factSettleStatus,jdbcType=NCHAR},",
          "PROD_INFO_STATUS = #{prodInfoStatus,jdbcType=NCHAR},",
          "PROD_APPRER = #{prodApprer,jdbcType=NCHAR},",
          "PROD_APPR_DATE = #{prodApprDate,jdbcType=TIMESTAMP},",
          "IMPRESSION_CNT = #{impressionCnt,jdbcType=DECIMAL},",
          "PRINT_COMP_CNT = #{printCompCnt,jdbcType=DECIMAL},",
          "BIND_COMP_CNT = #{bindCompCnt,jdbcType=DECIMAL},",
          "WHIN_QTY = #{whinQty,jdbcType=DECIMAL},",
          "DELI_QTY = #{deliQty,jdbcType=DECIMAL},",
          "MANU_COMP_DATE = #{manuCompDate,jdbcType=TIMESTAMP},",
          "AMT = #{amt,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=NCHAR},",
          "LOCKER_ID = #{lockerId,jdbcType=DECIMAL},",
          "LOCK_TS = #{lockTs,jdbcType=TIMESTAMP},",
          "MODIFYER_ID = #{modifyerId,jdbcType=DECIMAL},",
          "MODIFY_TS = #{modifyTs,jdbcType=TIMESTAMP},",
          "MODIFY_APPSVR = #{modifyAppsvr,jdbcType=NCHAR},",
          "MODIFY_MODULE = #{modifyModule,jdbcType=NCHAR},",
          "DATA_VERSION = #{dataVersion,jdbcType=DECIMAL},",
          "FACT_ID = #{factId,jdbcType=DECIMAL},",
          "CLOSE_DESC = #{closeDesc,jdbcType=NCHAR},",
          "MANU_DIST_ID = #{manuDistId,jdbcType=DECIMAL},",
          "字段45 = #{字段45,jdbcType=NCHAR}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TSoManu record);
}